### ISSUE TITLE
RFC: Ensure dependent services are set up in production before allowing a PR requiring schema changes to be merged

### ISSUE THREAD

**Issue by orta** [artsy/README#109]
## Proposal:

An example might be easier to think about:

> Let's say you have made changes to Exchange (which Metaphysics depends on) adding a new field to a type in it's API. You will need to make a PR to metaphysics to merge those changes into the metaphysics global schema. In making this PR, if the changes in Exchange haven't been deployed to production haven't been shipped to production then your PR to metaphysics will fail.

### Roughly

<p align="center"><img src="https://user-images.githubusercontent.com/49038/48570103-87442880-e8d1-11e8-91e6-6704b29e7e56.png" width="70%"></p>

If you want to make a change further down this list, the things above you need to be deployed in prod when you are making GraphQL schema changes.

This is currently happening on a force deploy with https://github.com/artsy/force/pull/3061 - but we'd like to move that behavior to run on metaphysics for its dependencies ( and eventually in Emission/Reaction too)

## Reasoning

This came up in the platform practice that the ability to be sure that all your dependencies are set up is valuable enough to introduce some friction to the process.

Doing this:

- Ensures we move dependencies into production more often 
- Ensures that PRs which do introduce changes to the system won't be deployed because another team is working in the same repo and does a deploy

## Additional Context:

You can see our discussion [in slack here](https://docs.google.com/document/d/11w4kveLJUOP1WyLFdUUSnEY2klJqNBfRfSnzAibAy4s/edit#heading=h.cgsjfypm4h5k)

**Comment by mbilokonsky** [comment]
I think this is a good idea. We have to be able to reason in isolation, and shouldn't be relying on remembering what got deployed to what server in what order etc. The fact is that if the MP PR under discussion got merged and deployed then there would be a crash, right? Seems like a simple win/win to me - it doesn't add complexity, that complexity is already there, it just provides a formal mechanism for dealing with it safely.

**Comment by joeyAghion** [comment]
If possible, I'd like to expand this RFC to generalize it from schema changes to _all_ changes. (Otherwise I'd have to make a separate RFC 😄.)

The GraphQL validation script enforces this for schema changes. A human process should enforce the same expectation when it comes to other dependencies. I.e., we should _model_ and _encourage_ pull requests to only be opened when their prerequisites are already in production. (This brings the same benefits described above of deploys being frequent, low-risk, and fast.)

Of course, `[WIP]` PRs are still acceptable for early feedback or whatever, but they should be clearly labeled as such and/or include blocking failures.

**Comment by mzikherman** [comment]
>  I.e., we should model and encourage pull requests to only be opened when their prerequisites are already in production.

This (anecdotally in my own experience) differs from the 'ideal' developer workflow. Which is, to make some backend/MP changes, _in concert_ with a front-end update. Sometimes you don't exactly know if everything is truly ready to go on the backend/MP as you're working on the front-end (Reaction component). Then, when you have something working on the front-end, and you're more confident in your backend/MP changes, they're then generally ready to PR at the same time.

So requiring the backend/MP (and within that group, backend _and then_ MP) to be deployed to production _before_ any front-end PR that consumes it feels a bit less than ideal, and adds some friction.

If people _do_ want that, then 👍 all the better, I just wanted to point out that the ideal workflow (IMO) conflicts with this slightly, so we should figure out a way to enforce/encourage this. Otherwise it might be hard to keep that discipline up.

**Comment by joeyAghion** [comment]
@mzikherman would designating those downstream PRs as works-in-progress (i.e., unmergeable) work? Or does the ideal workflow require that those PRs be _merged_?

**Comment by dleve123** [comment]
+1 to this!

I think solid next steps would be to do:

1. Add comparable checks in Reaction and Emission (to protect end-clients)
1. Add a check to MP

I think there's _slightly_ less risk to the MP side ATM as at least [Exchange has some tooling to enforce `_schema.yml` updates](https://github.com/artsy/exchange/pull/272), so I would prioritize Reaction and Emission first.

**Comment by orta** [comment]
> Do you have any thoughts on how this philosophy could be operationalized? 

We should have all the tools necessary to do it on CI (local schemas, tagged releases) that can let Peril or Danger figure it out at PR time.

**Comment by joeyAghion** [comment]
We should definitely enforce what can be done via tools. As far as non-schema dependencies, I first wanted to see if there was agreement about the goal. It sounds like there is, except for @mzikherman's observation about how it hampers the ideal dev workflow. Matt, see my question above about that.

If there's consensus, we should at least update [the playbook](https://github.com/artsy/README/blob/master/playbooks/engineer-workflow.md) to explicitly state the expectation that prerequisite releases are complete before PRs can be merged.

I think it _is_ possible to set an example about this and casually enforce it via PR comments like:
> This should be `[WIP]` until ... is released.

Or, harsher:

> Closed pending ... release.

Or, punnier:

> Don't forget **P**re**R**equisites when making a **PR**

**Comment by ashfurrow** [comment]
I'm 👍 on the schema change requirements; I'm also 👍 on the changes Joey mentioned as long as they're automated by tools. I think we should prioritize getting the schema requirements set up, though.

**Comment by ashkan18** [comment]
Sorry to be late in this, but we've been practicing this for Exchange -> MP -> Reaction -> Force 🚋 and has been really useful so all 👍for this.

One interesting side-effect of this is also we end up deploying downstream services more often.

**Comment by izakp** [comment]
I feel like I have half the picture and I want to see a full dependency graph.

Can we spec implementation more clearly in terms of the operations we want to perform for a given repo?
I.e. in terms of Metaphysics, on PRs to master we should:
- Check the proposed schema changes against Exchange production introspection API
- Check the proposed schema changes against Gravity production introspection API
... and so on, for all dependent services.

@ashkan18 in this sense I am not following you when you say you are practicing this for "Exchange -> MP -> Reaction -> Force" - can you point to me to this implementation?

In any case let's try and get https://github.com/artsy/force/pull/3061 working first, then come back to a Metaphysics implementation once well defined

**Comment by mbilokonsky** [comment]
We're doing this on local discovery now, too - it's not really a formal system exactly it's just that if a feature we need says "Add field X to model Y" then we create tickets to make the change in gravity, then make the change in MP, then downstream systems - and we set up the `is blocking`/`is blocked by` relations in JIRA to capture this.

The real question is, to what extent can this be automated? Can we catch errors in e.g. whether arguments are expressed in camelCase or snake_case? How much can we enforce via linting? Etc.

Discussing in the platform practice today the notion of grabbing the schema associated with a given commit hash makes some sense, but I'm not sure it captures all cases. As I understand it, we essentially have a KV map where the K is a commit hash and the V is the string schema as of that commit. But given that we're deploying these systems independently, how do we say that a given MP PR requires Gravity to be on commit X and Exchange to be on commit Y? Presumably both gravity and exchange could be on future commits, or could have been rolled back, right? So it feels like we still lack the ability to describe the system at large, or to enforce an RFC like this fully programmatically?

**Comment by ashkan18** [comment]
@izakp this has mostly been through PR process and pretty manual. Meaning when I make a MP change that depends on the Exchange change, we make sure the MP PR is WIP till Exchange has been deployed to production, once that gets deployed, we remove WIP from that PR.

**Comment by orta** [comment]
I think discussion this RFC is pretty much at a stalled point, some work got put on the platform roadmap. So, I'm going to close this up.

## Resolution
We did some of this notably the most critical part of force/metaphysics.

## Level of Support
2: Positive feedback.

#### Additional Context:
Interesting questions about the scope of this changes, and overall feasibility.

## Next Steps
N/A

#### Exceptions
N/A
