### ISSUE TITLE
Add a doc for the peer lab

### ISSUE THREAD

**Issue by orta** [artsy/README#11]
Could be the setup/setdown  todo list, a touch of history etc

**Comment by dblandin** [comment]
@ashfurrow @zephraph Hey! :wave:

This issue came up in Slack recently and I'd love to hear from either of you on:

1. Is this a helpful doc to include in artsy/README?
2. If so, would either of you be interested in writing up a draft?

cc/ @dleve123

**Comment by ashfurrow** [comment]
Yeah! I think it'd be helpful – happy to work on a draft on Monday's writing office hours. We've got [the original blog post](https://artsy.github.io/blog/2015/08/10/peer-lab/) and [the community website](https://peerlab.community) to draw from 👍
