### ISSUE TITLE
[RFC] New dependencies to Emission/Reaction go through the RFC process

### ISSUE THREAD

**Issue by orta** [artsy/README#117]
## Proposal:

Fail PRs which add new keys to the `dependencies` section on the `package.json` in Reaction / Emission. 

The fail would then be removed when an RFC is referenced in the body of the PR. Perhaps it canlook for a string like `RFC: [ur]` inside the body. Also support a message like `#skip_rfc` tag to skip the fail. 

## Reasoning

We'd like to find a better space to discuss additions to our two larger component libraries, it can be a shame to write a PR only to have it blocked on the discussion around adding a dependency

This is mainly to:

- Keep our dependency tree somewhat under control
- Ensure that we re-use dependencies, or avoid them if we have existing functionality you didn't know about
- Give everyone the chance to see and react to dependency updates

Some recent examples: 

 - [Formik in Emission](https://github.com/artsy/emission/pull/1063) (and yeah, I was a bit curt there, sorry @yuki24 (I think I was between meetings))
 - [React Spring](https://github.com/artsy/reaction/pull/1114)  

Slack:

 - [An SVG renderer for React Native](https://artsy.slack.com/archives/C02BAQ5K7/p1543269689301900) 🔒 
- [MapBox for React Native](https://artsy.slack.com/archives/D3PSUPD44/p1543350077001100)

## What an example RFC could look like

- [iOS Navigation Options](https://github.com/artsy/emission/issues/501)

## Exceptions:

Some PRs are pretty trivial, and so it should be possible to skip the discussion.

## Additional Context:

You can see our discussion [in notion](https://www.notion.so/artsy/27-11-2018-6161fc3144954d958c934a198e10087b) (it's a bit light on notes because I was the one taking notes and talking at the same time )

**Comment by ashfurrow** [comment]
I like this. I'd rather swing too much in favour of process and then pull back, than to continue without enough.

**Comment by damassi** [comment]
I'm into it too -- let us use Force's [`package.json`](https://github.com/artsy/force/blob/master/package.json#L52) as an example! 

@orta - Does this also apply to dev tooling / `devDependencies`? (I imagine this as only relating to deployable `dist` code.)

**Comment by orta** [comment]
Not to `devDependencies`, no - only distributed code

**Comment by javamonn** [comment]
We should do what we can to encourage that the necessary discussion happens upfront - failing a PR is probably too late as usually by that time your implementation is pretty coupled to the dependency that you introduced.

This will introduce a some overhead in some product work ("why is this small ticket taking so long?") but perfectly fits the description of a "spike" ticket.

**Comment by orta** [comment]
We've shipped a doc that gives heuristics on whether a dev should have an RFC In https://github.com/artsy/README/blob/master/playbooks/dependencies.md

Will add a Peril rule that detects the changes and notes that it may need an RFC

**Comment by orta** [comment]
OK, I'm going to close this as "we agree on it"

and I'll ship an RFC template ASAP
