### ISSUE TITLE
[RFC] Updates to On-Call Process: Jira Ops + Status Page

### ISSUE THREAD

**Issue by sweir27** [artsy/README#130]
## Proposal (mini)

More below, but this proposes a new process to keep track of incidents and communicate their status via tools including Jira Ops and Status Page.

## Reasoning

As our on-call process has evolved, we’ve identified a few areas of improvement:
- It’s non-trivial to analyze trends of incidents and keep track of follow-ups. Currently this happens with a combination of people updating a trello board, making Jira tickets, and manually tracking incidents after-the-fact in a spreadsheet.
- We don’t yet have a good way to alert external parties when we’re having downtime. See https://github.com/artsy/README/issues/108 for more detail.
- It’s difficult to separate the act of solving an issue with communicating impact to stakeholders. See https://github.com/artsy/README/issues/63 for a potential solution to this problem.

### Goal of these proposed changes
_To make it easy for anyone at Artsy to raise incidents, keep track of which incidents are occurring/have occurred, and their potential impact and follow-up._

There are many ways to improve our fledgling on-call support process, and these changes do not attempt to solve all of them. 

Our _ultimate_ goal is to create a process that is transparent for both incident responders and incident reporters. Accomplishing this will at least involve changes to our process on engineering, changes to how stakeholders interact with our team, and potential additional tools and budget.

The changes proposed here focus only on the first part: how we can improve the Engineering team’s process.

## Exceptions

Intentionally not included here are:
- Updates to the process for incident-reporters. We still expect them to go through the #incidents Slack channel. 
- A way of addressing our “notification problem” and formal escalation paths to ensure that we have true 24/7 support. We know that setting up slack notifications is not necessarily sufficient to wake someone up in the middle of the night, and there are tools we can pay for that are designed to help with this. This point is important but to keep the changes here manageable, it will be a follow up.
- Updates to our process for triaging and fixing bugs. Bugs will still be created on the universal bug backlog and looked at by product managers.
- A formal way of escalating bugs that recur. Although, a side effect of the changes proposed could potentially help this without requiring additional processes.
- Workflow optimizations like slack notifications or a slackbot to help people raise incidents with a slash command.

Some of these, especially the first two items in that list, are top-of-mind. They're not in this proposal because we felt it would be too much to introduce all at once and want to give this process a try first.

## Additional Context

Join the [#on-call-working-group](https://artsy.slack.com/messages/CE6URL06M/) slack channel to see discussions around this and other topics related to how we want to handle on-call.

See https://github.com/artsy/potential/pull/134 for the initial explanation behind our current process (which has since evolved!).

## How is this RFC resolved?

If we decide to move forward with this RFC, the next steps will be to:
1. Update the existing support playbook in this repo to reflect these process changes.
2. Add a link to the Jira Ops board in the slack topic in #incidents
3. Schedule a training session to walk through the new process in real life 🎉 
4. Add new fields to the Jira Ops issue template:
    - Reported at
    - Acknowledged at
    - Resolved at

## Proposal (meaty)

If this is added to the master support playbook, we'd also like to include:
- A diagram of the lifecycle of an incident
- A separate section to describe incident severity (right now it's included inline)
- Add pictures 😅 

#### Step 1: Alert
1. Incidents can be raised by automated (based on alerts that we’ve set up) or manual means. In both cases, the on-call team is notified of incidents first through a message to the [#incidents](https://artsy.slack.com/messages/C9RK0BLEP/) slack channel.

#### Step 2: Raise
1. When an incident is raised in the channel, the on-call team first **tracks the incident** by creating a ticket in Jira Ops, based on the information they know at that time. Some workflow steps:
    - Link to the slack thread where the incident was first reported in the description of the ticket.
    - Take your best guess at the other information, it can always be edited later.
2. In the original slack thread, link to the newly-created incident

#### Step 3: Assess and Identify
1. A member of the on-call team marks the issue as FIXING. This person will be automatically assigned to the issue, and they are designated the “Incident Manager” for the duration of the incident resolution. This person is responsible for **facilitating** the resolution. They may or may not be the person equipped to fix the issue. Other responsibilities, like communication, should be delegated to the other on-call team member if necessary.
2. Determine the severity of the incident by trying to reproduce the problem and trying to capture the answers to the following questions in the Jira Ops Incident:
    - How many people (or partners, etc.) does this affect?
    - Have you been able to reproduce?
    - Is this a new problem or something that we are aware of?
3. Update the severity on the ops ticket. The following definitions are borrowed from [Atlassian's playbook](https://www.atlassian.com/software/jira/ops/handbook/responding-to-an-incident):
    - **Critical**: A critical incident with very high impact (i.e. customer data loss; customer-facing service like CMS is down)
    - **Major**: A major incident with significant impact (i.e. a large number of images are not showing up; a small number of partners cannot access CMS)
    - **Minor**: A minor incident with low impact (i.e. a single user cannot place a bid in an auction; a page linked from the app is showing a 404)
4. If the reported incident does not qualify for an immediate response:
    - Direct stakeholders in the slack thread to a product team’s channel to ensure that a Jira Issue is tracked for this possible issue
    - Link the Jira incident to any relevant bugs that are tracked (and create an additional one if necessary)
    - Mark the incident as CANCELED

#### Address Incident
- **Investigate --> Identify --> Escalate --> Fix**
  - The Incident Manager uses the Jira Ops slack integration to start a slack channel for the incident, and invites people who they think could help investigate and fix the issue.
    - Pro tip: If you subscribe to many channels, this one could get lost. **Star** it so it appears at the top of your list during the duration of the incident.
    - The slack channel is for discussing the incident's resolution. Keep communication to stakeholders confined to the original slack thread, if possible.
  - [The rest of this follows our current process in the playbook]
- **Communicate**
  - The Incident Manager (or someone else they have delegated to) handles communicating any updates to the incident. This includes:
    - Posting updates in the Jira Ops issue when new information is discovered. This will create a useful timeline that we can look back on as a post mortem.
    - Posting updates/answering questions in the slack thread in #incidents for stakeholders.
    - Keeping our public status page up to date. Any incidents with a severity of Major or Critical should be communicated externally via the status page. Communication does not have to be detailed. The most important thing is acknowledging issues and communicating progress towards a resolution. Use the status page integration on the Jira Ops ticket where possible.

#### Resolve
- Incidents are resolved when the immediate issue has been addressed. After that, the team needs to make sure all follow-up items are tracked, and the incident clearly reflects this state.
  1. Create any necessary follow-up tickets either in the bug backlog or a specific team’s project board. Link these from within the incident ticket.
  2. Post any final updates to the incident ticket.
      - Update timestamps
      - Mark the ticket as RESOLVED
      - Add any additional labels or fill out fields that may be relevant later.
  3. Resolve any outstanding incidents on status page
  4. Post a final update to the original slack thread
  5. If the incident was Critical or Major, create a post mortem following the guidelines in our [post_mortems repo](https://github.com/artsy/post_mortems).

**Comment by ashfurrow** [comment]
Yeah, sounds good. I'd sleep easier knowing that I'd get a call if something were wrong (instead of waking up every half hour and checking for Slack notifications). I'm also a huge fan of diagrams 👍

**Comment by joeyAghion** [comment]
> Schedule a training session to walk through the new process in real life

I think a few choice screenshots would be a powerful alternative/supplement to any training, and be available forever for self-service.

> In both cases, the on-call team is notified of incidents first through a message to the #incidents slack channel.

This doesn't cover automated notifications to #alerts.

> The Incident Manager (or someone else they have delegated to) handles communicating any updates to the incident. This includes...

This section is burdened by the many different forums (incident-specific slack channel, #incidents slack thread, Jira Ops updates, and public status page). I felt this too during the few incidents I was personally involved in (there was a lot of communication necessary to resolve _who_ would communicate _what_ to which _audience_). Could we radically simplify it to:
* #incidents is for non-on-call people to raise possible incidents or follow up (questions, etc.) about existing incident threads.
* Resolution happens exclusively in the dedicated Slack channel associated with the Ops ticket.
* Any meaningful updates or discoveries are recorded (by the assignee, by default) to the Ops ticket.  Significant milestones (new incident, availability changes, incident resolved) are recorded this way _and_ published to the public status page.

I'm just trying to remove ambiguity between these forums. Alternatively, we could drop the incident-specific channel approach altogether and continue to use threads in #incidents. That would remove one big overlapping medium, and maybe is more natural for people than the one-off channels that might be hard to keep on top of.

**Comment by sweir27** [comment]
@joeyAghion Agree with you on these points-- thanks!

I've been appreciating the incident-specific slack channel since threads can easily become clunky and it's difficult to intersperse answering questions + debugging. I'm curious what others think though (cc @erikdstock @dleve123 @ansor4 @ashleyjelks + others who have used them).

**Comment by dleve123** [comment]
> I think a few choice screenshots would be a powerful alternative/supplement to any training, and be available forever for self-service.

I respectfully disagree here. I think for something like an incident response procedure (where accuracy and timeliness are of the essence), everyone should go through training. Incident Response training is a pretty common thing FWIW (it's part of Aptible's Gridiron product for example).

> This doesn't cover automated notifications to #alerts.

I think there should be an expectation that on-call people actively monitor #incidents and #alerts, at least for the short term.

> I've been appreciating the incident-specific slack channel since threads can easily become clunky and it's difficult to intersperse answering questions + debugging. I'm curious what others think though (cc @erikdstock @dleve123 @ansor4 @ashleyjelks + others who have used them).

I agree with @joeyAghion's recommended communication architecture. If I understand correctly, I think you are suggesting that our "public API" to rest of the company should be via the JIRA ticket, and to the outside world should be via the Status Page. We could set up a Slack integration to pipe information from JIRA to #incidents so that business stakeholders can read this information from well-know forums.

I'm a bit hesitant to always automatically pipe JIRA Ops ticket updates to StatusPage, but happy to give it a try to see how it goes.

The whole incident specific Slack thread in #incidents would no longer be part of the process, is that correct? Personally, I find that threads can often hide information, so I think not using threads for any convo in #incidents is a good idea.

**Comment by sweir27** [comment]
Thanks all for the comments!

I'm going to close this and follow up with a PR to readme.
