### ISSUE TITLE
[RFC] Improve definition of point people on projects

### ISSUE THREAD

**Issue by jonallured** [artsy/README#146]
## Proposal

Provide definition and guidance around the point people for a project.

We want projects to be owned by teams overall, but lots of temporary ownership over projects makes it hard to address technical debt, or to ensure a long-term vision on a project. One solution to this is to define point people, who are responsible for the long-term technical direction of a project, especially as a project can change ownership between teams during its lifetime.

The point people for a project should change over time as people come and go, and also grow if the project evolves in being more significant to us.

This RFC is about trying to document a consensus on what point people’s responsibilities are, and how we can improve code ownership at Artsy.

## Reasoning

Having a clear definition of what it means to be a point person on a project at Artsy removes ambiguity. Defining what this role means helps those new to Artsy get up to speed more quickly.

We want to be confident that someone is always looking out for the overall vision of our projects so having an organic way to change who these people are helps with this confidence.

Providing a path for new people to own things helps them feel like they are a part of the team.

## Project Impact and Point People

The impact of our projects varies and this affects the role of point people and the number required to provide confidence that the long term direction of the project will be covered adequately.

Consider these projects:

* [Force](https://github.com/artsy/force)
* [Gravity](https://github.com/artsy/gravity)
* [Waves](https://github.com/artsy/waves)
* [Reaction](https://github.com/artsy/reaction)
* [Currents](https://github.com/artsy/currents)
* [Causality](https://github.com/artsy/causality)

One way to distinguish between these projects is the level of impact each has on Artsy's business - as a project has more impact it should be staffed by more point people.

The aim of this RFC is to provide:

A definition for those stages
A process for either bumping a project up/down
A process for requesting changes for a point person

## Exceptions

We aim to have every active project in Artsy assigned to a team (see the linked project list below) and there’s a reasonable argument to be made that this can be enough for some projects. We’d have to get to that when we get there.

## Additional Context

The Artsy Project List in [artsy/potential](https://github.com/artsy/potential/blob/master/Project-List.md).

We want people to feel personal growth at Artsy and one way for engineers to do that is to leverage their business impact. By providing straightforward definitions and processes we can ensure a fair playing field regardless of anyone’s assertiveness.

## How is this RFC resolved?

* A document in README defining the responsibilities of point people
* A document in README on the stages of a projects maturity and impact
* A recommend way to describe the project in it’s README via these stages
* A discussion on ways to evaluate or request an evaluation of the point people (ideally we do
  this somewhat regularly too)
* PRs to a bunch of our popular repos updating their Meta sections on their
  READMEs

Note: this RFC co-authored with @orta 👬

**Comment by ashfurrow** [comment]
> We want people to feel personal growth at Artsy and one way for engineers to do that is to leverage their business impact.

I really like this part – increasing business impact is something that we've encouraged in Artsy engineers, but not always evenly. Newer team members and developers who focus on less widely-applicable tech (like iOS for example 👀) have sometimes struggled at Artsy to expand their business impact. I don't think it's specific to Artsy, this is just a people thing that we've dealt with so-far on a person-by-person basis. Systemic solutions like this RFC are a better approach. Rotating point people (and rotating tech leads, something we do _on paper_) is a great way give people opportunities to expand their impact 👍

**Comment by joeyAghion** [comment]
I was interested in building the team-based project list linked above based on frustrations with how "point-people" associations worked in practice:
* A relatively small set of people were point on a large set of projects.
* Since it was an informal status and separate from staffing/planning decisions, point people often didn't have capacity for actual work (bugs/maintenance) on the project (though they were usually good sources of PR feedback).

I'm all for refining who/how point people work, but wanted to provide that context. That balance of team capacity and plans with system needs is always difficult.

**Comment by mbilokonsky** [comment]
I see a distinction between your arguments for clarity around 'point people' and your arguments for clarity around 'project status', e.g. maturity etc. I don't necessarily see these two as coupled - I think we could have a really productive orthogonal discussion about each of these proposals.

Personally, I like the idea of reifying project maturity (especially if we define like five states with very clear transition points) but am increasingly opposed to point people, I think, being explicitly tracked.

I kinda like the idea of point teams, though, and then each team can be responsible for deciding how they want that to work. Is one team-member the person who represents that team's expertise on that project, or does the team rotate people through their projects to build institutional knowledge etc?

**Comment by mbilokonsky** [comment]
Project Maturity (my initial attempt at an ontology):

0. Red
- specify point team
- put all initial feature goals into readme (short w/ links to JIRA)
- track features in readme crossing them off as implemented.

<transition: feature-complete and staged>

1. Yellow
- all features represented in passing tests
- "prod checklist" in readme, tracking everything necessary to support this in prod

<transition: launched into production>

2. Green
- running and working in prod
- whole history of every requested feature still exists in README
- new features follow a similar path

<transition: service is involved in an incident or other serious issue which requires updates>

3. Mature
- readme updated with incident history and changes
- tests ensure incident can't repeat

I'm not sure if that makes sense exactly, but it's my initial stab?

**Comment by jonallured** [comment]
I’ve sorta lost steam on this one, but I’d like to see if I can turn that around and get something moving here.

@mbilokonsky I think you’re right that there are actually two things here - one about describing point people and another about defining project states. The reason I think it’s valuable to talk about them together is that the state of a project impacts the attention people are paying to the project. Using your Project Maturity stages, I’m not concerned about ensuring point people are paying attention to a project while it’s red or yellow - that’s when things are the hottest and things are rolling well. It’s once a project gets green that I think we have an opportunity for improving things.

It’s been my experience that once a project hits the production phase of its life, the technical direction and vision tends toward zero. It’s much more common at this point for a project to experience drive-by PRs that don’t necessarily contribute to larger goals for the project. Heck, I'd argue that most of our project don't even have long term goals.

My feedback on your initial stab at Project Maturity is that it doesn’t address this long-term technical direction and vision. This is what I feel like we’re missing and I want to see about improving. A good example here is Currents. This project has evolved quite a bit over it’s lifetime at Artsy, but let’s take one technical choice and examine it:

Currents takes in CSVs and images and then transforms them into Artwork records in Gravity. It uses a third-party called [Cloudinary](https://cloudinary.com/) to accept the uploads and do some processing. This may have been a fine technical choice at the time, but it hasn’t aged well. Now that Rails has included support for uploads with Active Storage, all the features we’re paying a third party for are things we can do ourselves.

I believe recognizing opportunities like this to improve the technical direction of a project is the role of a point person. So that’s what I really want out of this RFC - I want to document this as their role and then provide a mechanism for point people to change. On top of that, I think it’s worth recognizing that very large projects like Gravity or Force are probably better served by having a handful of point people assigned.

**Comment by jonallured** [comment]
## Resolution

We decided to do it.

## Level of Support

4: Acceptance, with Little Feedback.

## Additional Context:

Not much discussion, moving forward.

## Next Steps

A PR to README documenting:

* the role of point people
* a process to change point people
* a note that large impact projects should have a handful of point people

## Exceptions

none
