### ISSUE TITLE
[RFC] Merging Hokusai's commit deployment and application configuration strategies

### ISSUE THREAD

**Issue by izakp** [artsy/README#152]
## Proposal:

Automate the rollout of configuration changes to Kubernetes yaml specifications along with code changes.  Adopt ideas from or integrate [Helm](https://github.com/helm/helm) into Hokusai to create a deployment manifest for each deployment, interpolating the deployment tag (Git commit SHA1) and timestamp, and save each manifest in Kubernetes as an audit log, which would facilitate rolling code and configuration forward and backwards in concert.

## Reasoning

Hokusai was originally designed to decouple rolling out code changes (i.e. `hokusai [staging|production] deploy {COMMIT_SHA1}`) from configuration changes pertaining to that application's environment (i.e. `hokusai [staging|production] update`).  Initially the overhead of Helm seemed unnecessary given our configuration changes were very infrequent as compared to code changes, and Helm is designed for semantic versioned releases.  However, this has caused us problems.

We have seen cases where this decoupling is a source of confusion, as the `update` command runs the command `kubectl apply -f {path-to-local-hokusai/staging-or-production.yml}` against the local checkout of the repo, so in essence, the developer's local git state becomes the source of truth.

Also maintaining the `staging` and `production` image tags as pointers to the currently-deployed Git-SHA1 tag has forced us to bust the docker cache and always check the latest image for these tags, which has had downstream effects resulting in downtime due to ECR unavailability.

This proposal is to adopt an org-wide deployment strategy that is fully automated for code as well as configuration changes.  However, it will be a breaking change and require migration for projects as well the version of Hokusai running against those projects.  The [release 0.5.1](https://github.com/artsy/hokusai/releases/tag/v0.5.1) introduces a compatibility check to facilitate this migration.

## Exceptions:

The `hokusai pipeline promote` deployment strategy will have to be abandoned, as it simply gets the deployed image on staging and promotes it to production, without regard to any configuration changes.

This change would propose to interpolate variables when creating a new deployment, rather than setting up a new project, so https://github.com/artsy/artsy-hokusai-templates would also change in structure (i.e. the templates would not be rendered when creating a project, but there will be template variables in yaml configuration)

The `staging` and `production` tags would become redundant, and this might very well be a good thing, as we have seen the `staging` tag conflicts with the `staging` branch in Positron's repo and we currently don't push Git tags because of it.  cc @dleve123 @eessex 

## Additional Context:

@alloy has brought up issues of revision history and rolling back, which needs to be done across multiple deployments (i.e. Puma / Sidekiq for a given application)
@ansor4 and @joeyAghion @dleve123 and myself recently encountered a strange situation where we released a config change for a Gravity sidekiq bidding worker, before the code change that referenced Sidekiq config checked into the project, and built into the image.

## How is this RFC resolved?

- Consensus around our deployment strategy across repos
- Implementation of a new deployment strategy in Hokusai
- Migration of existing projects to the new deployment strategy
- Developers upgrading Hokusai, possibly being required to switch between versions of Hokusai between projects during the transition, or rely on CI for deployments altogether.

**Comment by ansor4** [comment]
An out of the box solution could be something like https://www.weave.works. They use something they call GitOps (https://www.weave.works/technologies/gitops/) in which all config changes are tracked via git.

In a previous discussion, @izakp brought up a good point in that this would be difficult to integrate into our open source projects. If we end up having a private repo to track configs, it could introduce drag on deploys if changes to the config repo end up blocking changes to other repos.

Since Helm was mentioned, this is how weave.works approaches Helm in a GitOps way : https://www.weave.works/blog/managing-helm-releases-the-gitops-way

**Comment by dleve123** [comment]
> as we have seen the staging tag conflicts with the staging branch in Positron's repo and we currently don't push Git tags because of it. cc @dleve123 @eessex

Small thing, but IDK how much we should read into this Git configuration -- I wonder if the `staging` branch is a relic of a pre-k8s architecture? Have we validated the importance / relevancy of this decision yet?

> This change would propose to interpolate variables when creating a new deployment, rather than setting up a new project, so https://github.com/artsy/artsy-hokusai-templates would also change in structure (i.e. the templates would not be rendered when creating a project, but there will be template variables in yaml configuration)

Do you have a vision of what Hokusai's new deployment API would look like?

Re @ansor4's investigation of 3rd party tools: I'm all for finding an existing solution to this problem, we're surely not the first organization to hit these types of issues. With that said, I think it's powerful to have infrastructure code living within the same repository as application code for a given service: I think it can help ameliorate against the "out of sight, out of mind" mentally that's all too easy to embrace with systems engineering / infrastructure, so I just want us to consider code organization structure as we evaluate alternatives.

---

@izakp While we iterate on a canonical, "1 deployment to rule them all" approach (this conversation), I wonder if there's a way for us to leverage CI to detect and rollout k8s changes with `hokusai [staging|production] update` in the meanwhile.

Could we express the following in CircleCI: "If there were changes to relevant hokusai configuration files, then run a hokusai update and hokusai restart"?

Having CI manage these types of changes would at least remove a dev laptop from being the source of truth for infra deployments, and introduce more rigor and automation to our existing approach.

**Comment by izakp** [comment]
I really like the approach in the links @ansor4 posted.  Thanks for the excellent examples.  @dleve123  in terms of a vision for what the new API would look like, I think the link https://www.weave.works/blog/managing-helm-releases-the-gitops-way provides a good example, in the section "Flux Helm release fields" - it essentially introduces a pre-processor that creates a deployment manifest with the updated image tag.  In this case, Flux is overloading variables that are referenced in Helm templates, and setting `spec.values.image` to the image tag to be deployed.

Hokusai would be that pre-processor, and you'd be able to reference template variables in Yaml spec, 
so for instance in https://github.com/artsy/gravity/blob/master/hokusai/production.yml#L37 the line `image: 585031190124.dkr.ecr.us-east-1.amazonaws.com/gravity:production` would become `image:{{ repository }}:{{ tag }}`

We could start running `hokusai [staging|production] update` via CI in the meantime - Kubernetes won't roll out anything if it detects there are no changes between the spec and what it is already running.  The exceptions here are projects relying on the `hokusai pipeline promote` command to roll out production code manually.  Hence my inclination to abandon it.

**Comment by izakp** [comment]
> We could start running hokusai [staging|production] update via CI in the meantime - Kubernetes won't roll out anything if it detects there are no changes between the spec and what it is already running.

We can start automating config changes, but I should point out the caveat that running `hokusai production update` in CI followed by `hokusai production deploy {SHA}` will trigger multiple deployment rollouts and config will go out before code does.  Thinking of the case where recently @joeyAghion and @ansor4 added a new type of Sidekiq worker, that required a new [deployment](https://github.com/artsy/gravity/blob/master/hokusai/production.yml#L448) in concert with [code changes](https://github.com/artsy/gravity/blob/master/config/sidekiq_bid.yml) that configured the new worker.

Because developers may have other implicit assumptions, I'd rather not take the halfway step to automate config rollout with the current implementation until we can roll code and config out together.

**Comment by dleve123** [comment]
> One question I have: where would updated config values fit into the more automated pipeline (e.g., an increased ..._TIMEOUT)? Would that continue to depend on a developer running set and refresh commands?

FWIW, I'm not sure how much of a problem this is? Updating/deleting config is as simple as a `hokusai [staging|production] env set ...` which seems low risk to me and independent from the local environment that's running it. So a problem with this is _not_ immediately apparent to me, and I'd recommend not solutioning around (of course until we identify a problem).

> Because developers may have other implicit assumptions, I'd rather not take the halfway step to automate config rollout with the current implementation until we can roll code and config out together.

Something that seems analogous here is the relationship between Rails application code and Rails migrations. Folks know/learn that usually new containers need to support _old_ db state _before_ the db in question is migrated, and often teams adopt workflows where database migration PRs are merged and deployed before application change PRs (or vice-versa, depending on the change - when dropping a column for example).

All that is to say that while infra code and app code might be related, we could think about deploy sequencing _and_ move the `hokusai [production|staging] update` runtime to CI. Hope that makes sense -- might be a bit more in the spirit of incremental engineering as well.

**Comment by bhoggard** [comment]
Using CI for promotions would also prevent us from having several people deploy at once.

**Comment by orta** [comment]
One approach that allows configs to both live in public code and be deployable with your app is what I use for Peril: https://github.com/danger/peril/blob/master/api/now.staging.json

The env config uses reference variables that are set per-deployment for private things, and updates to the now json get shipped with the deploy (you'd still have to configure it before, but it won't be used till the deploy ) - https://zeit.co/docs/v2/deployments/configuration/

**Comment by izakp** [comment]
Thanks for the comments all!  Closing this but will take your feedback into consideration in Hokusai and will and link any changes in the deployment strategy back here.
