### ISSUE TITLE
RFC: New Incident Review meeting

### ISSUE THREAD

**Issue by SamRozen** [artsy/README#165]
## Proposal:

Start a new biweekly "Incident Review" meeting series.

Agenda:
- An incident will be added to the agenda after it's resolved. 
- For each incident we'll review the [post mortem](https://github.com/artsy/post_mortems), discuss follow up actions items and share learnings.

Invite list: 
- All engineering will be optional.
- People most involved with the incidents will be added as mandatory participants.

Meeting should be cancelled if there's nothing on the agenda.

## Reasoning

We want to maximize the learnings from past issues and reduce the likelihood of repeating the same mistakes. Incidents are an amazing opportunities to reflect and identify what we can do better.

## Exceptions:

¯\\_(ツ)_/¯

## Additional Context:

This was discussed previously in a platform pratice meeting and we agreed to have that discussion here instead before moving forward.

**Comment by orta** [comment]
IMO, this makes sense. 👍 

The idea of the meeting being scheduled but unreliable might undermine it to mainly just being a few core folk who almost go every time, but it's a good step forwards rather than trying to encourage ad-hoc retrospectives.

**Comment by SamRozen** [comment]
## Resolution
We decided to do it.

## Level of Support
2: Positive feedback. or 4: Acceptance, with Little Feedback. (I'm not calibrated enough on this scale)

## Next Steps
@SamRozen will start scheduling this meeting series and own the agenda. We'll start from #incident-30 onwards.

**Comment by SamRozen** [comment]
This is now implemented here: https://www.notion.so/artsy/Incident-Reviews-725052225efc49e78532b13e166ba3c7
