### ISSUE TITLE
Fill out doc on what is expected for mentors

### ISSUE THREAD

**Issue by sweir27** [artsy/README#17]
Shell is here: https://github.com/artsy/README/blob/master/onboarding/mentors.md

Should/could include things like:
- What makes a good mentor?
- What is the expectation of a mentor?
- What should mentors remember to do?
- What role does a mentor play in the first few weeks of someone starting?

**Comment by zephraph** [comment]
I think it'd be good to have a light checklist for a mentor of general topics they should cover. 

Things like

- Checking to ensure a mentor has all their dev stuff setup
- Spending some time to talk about culture and it's importance to the team
- ...

**Comment by erikdstock** [comment]
Resolved by #102 😃
