### ISSUE TITLE
[RFC] Sharing Teams Retro Boards

### ISSUE THREAD

**Issue by ashkan18** [artsy/README#172]
## Proposal:

Share links to different teams retro boards publicly across PDDE.

## Reasoning

Retros are great places to discuss our internal team processes and possible places for improvements. Whats possibly missing in our current approach is sharing the results of these retros and finding possible common pain points and improvement areas. 

For example i've been in retros from different teams where something like _missing integration tests_ has come up few times. Currently these stay within the team but if we share these boards across PDDE, these common patterns will emerge and we can act upon them easier.

In the past places, each team's retro boards were actual post its hanging on the wall for the rest of the week so you could just pass by the boards and see whats going on in other teams and possibly detect some common patterns and do a wider team effort to fix them.

## Exceptions:

None?

## Additional Context:

The only issue I can think of is, knowing these retro boards are currently within only each team, I can imagine some people may not feel comfortable about opening out to public in PDDE but I think overall we'd benefit more from having them as public.

## How is this RFC resolved?

Finding a proper place to share links to retro boards

**Comment by l2succes** [comment]
That's a great idea IMO, that would also give us an opportunity to identify and address recurring themes and related concerns across PDDE and would allow us to allocate resources for solutions accordingly.

**Comment by sweir27** [comment]
Very into this idea!!

I don't see any problem sharing them. Technically all of our boards are accessible, it's just probably not obvious how to find them.

**Comment by orta** [comment]
+1 - anything to avoid siloing info

Perhaps a potential page?

**Comment by ashkan18** [comment]
i actually thought about a page in potential, but i wonder if thats still kind of hidden, i was more thinking about slackbot type of thing but not sure how it should/could work

**Comment by joeyAghion** [comment]
I especially think it might be useful to share _action items_ from retros, since those represent opportunities for other teams to learn from or borrow. (They're essentially a list of what we learned from each sprint.) Maybe that would help keep the ideation/discussion a safe space?

**Comment by ashkan18** [comment]
good point on only sharing _action items_! 

So im thinking maybe we do:

- Add a new repo (or reuse Potential)
- Have the moderator of the retro of each team to open an issue in github on repo ☝️  in specific format (use issue template)
- Have Peril capture that issue and post it to slack
- Possibly on Engineering stand up go over common patterns.

**Comment by dblandin** [comment]
This all sounds great! :100: 

+1 to sharing actions items, issues in artsy/potential, and notifications via Peril :+1:

**Comment by ashkan18** [comment]
# Resolution
Each team goes through their retro meeting. Once action items are defined, the person who has run the meeting can open a github issue using new `RETRO_ACTION_ITEM` issue template. Once this issue is created, the action items will be shared with rest of the team. 
Once issue is created, we use Peril rules to post messages to #dev slack channel so everyone can get notified about this.

# Level of Support
2: Positive feedback.

There were concerns about this possibly making retro's less open since it can expose team's dynamics and concerns out. This was resolved by only sharing _action items_ of each retro which should be actionable so therefore public :) but still it's up to the team to decide what items they want to share with rest of engineering.

# Next Steps
@ashkan18 to create issue template and setup Peril's integration for slack messages. We will also announce this in our stand up and also try to nudge people for first few weeks to get the habit going :)

# Exceptions
None that I know of yet.

**Comment by ashkan18** [comment]
alright this is ready to be closed, from now on, a TL or person running retro can go to https://github.com/artsy/potential and create a [new issue](https://github.com/artsy/potential/issues/new/choose).

![image](https://user-images.githubusercontent.com/1230819/56211765-9c5ee800-6026-11e9-97fb-4d1e0eb9aa28.png)


Then choose Retro Action Item template for creating the issue by clicking "Get Started".

Then in the issue title set their team and sprint number and in description fill in action items and assignee. Example: https://github.com/artsy/potential/issues/244

This will post a slack message in #dev and share the action item with other team members.

<img width="675" alt="Screen Shot 2019-04-16 at 9 02 16 AM" src="https://user-images.githubusercontent.com/1230819/56211861-cfa17700-6026-11e9-88d1-0af30b55b559.png">

Its up to the team to pick which action item they want to share and if they want to create separate issue for each action item or have everything in one.
