### ISSUE TITLE
[RFC] Align on "technical spike"

### ISSUE THREAD

**Issue by starsirius** [artsy/README#175]
## Reasoning

Following the PDDE Q1 retro, while teams can operate and execute sprints differently, it'd be useful the organization aligns on some terminologies and shares best practices. The Galleries team had a discussion about what a technical spike is, and I feel it's a good example to get alignment.

### The goal of a technical spike
_“A spike is an investment to make the story estimable or schedule-able."_ [(1)][1]

When we are unable to estimate a use story from a technical perspective, it usually indicates the story is too big or uncertain. If it's too big, we should break it down to be reasonable and estimable. If it's uncertain because of technical unknowns, a technical spike can be used to reduce uncertainty. The goal of a technical spike should be to unblock the team to be confident making priority and planning decisions.

Some examples when a technical spike can be used:

- The team may not have knowledge of a new domain, and spikes can be used for research to familiarize the team with a new technology or domain.
- The user story may contain significant technical risk, and the team may have to do some research or prototyping to gain confidence in a technological approach.

### A technical spike is not...

- "Small" projects: in the past, "spike" has often been used when discussing a small unit of work. The definition of a technical spike in this RFC would exclude these cases, but a technical spike could lead to small projects that are well-ticketed reasonably.
- Unclear issues: under this definition, spikes are meant to specifically provide clarity, and they have a clear start and end point. So while a spike should be considered when we need to better understand a problem, it should not be applied without intent, goals, and time criteria. In other words, a spike is meant to address a specific scenario or issue, and it shouldn't be a matter of "this ticket is confusing, let's do a spike on it and see if we can figure out what it means."

### Guidelines

- A spike should have clear questions to answer or acceptance criteria.
- A spike should be time-boxed.
- A spike should be demonstrable. This brings visibility to the team and builds shared responsibility.
- The team should consider implementing the spike in a separate sprint from the resulting stories.

## How is this RFC resolved?

The team agree on the terminology and can use it to facilitate planning on product teams.

[1]: https://www.leadingagile.com/2016/09/whats-a-spike-who-should-enter-it-how-to-word-it/

**Comment by mdole** [comment]
I like this definition! I think it's worth calling attention to what this does **not** include as well; things like:
- "Small" projects: in the past, "spike" has often been used when discussing a small unit of work. The definition of "spike" in this RFC would exclude these cases, which I think makes sense—sometimes those "small" projects end up getting larger and are not really spikes.
- Unclear issues: under this definition, spikes are meant to specifically provide clarity, and they have a clear start and end point. So while a spike should be considered when we need to better understand a problem, it should _not_ be applied without intent, goals, and time criteria. In other words, a spike is meant to address a specific scenario or issue, and it shouldn't be a matter of "this ticket is confusing, let's do a spike on it and see if we can figure out what it means."

These interpretations are my own; feel free to disagree or discuss 😄

**Comment by starsirius** [comment]
Great feedback @mdole. I included it in the RFC under section "A technical spike is not...".

**Comment by starsirius** [comment]
## Resolution
We decided to go with the definition.

## Level of Support
2: Positive feedback.

## Next Steps
We will use the aligned term going forward.

#### Exceptions
N/A
