### ISSUE TITLE
Link to "onboarding" or "overview" docs for each product team in onboarding

### ISSUE THREAD

**Issue by sweir27** [artsy/README#18]
Somewhere in our onboarding docs, we should link out to where one can find a high-level view of what each product team is responsible for.

This may or may not already exist for those teams (and will likely be in Notion?). Possible topics include:
- Link to the team's JIRA board
- Rough schedule
- What the team is responsible for
- Who is the current tech lead/PM/design/analyst
- What are the main systems that the team uses for their day-to-day work?
- For someone just browsing the team, what are notable projects that the team has done or is working on/thinking about?

**Comment by orta** [comment]
I don't think there's an org chart-is thing in notion - I tried to find it for the README, and opted to just link here instead: https://www.notion.so/artsy/Product-470238180cf94c87906ef1d3ee259e05

**Comment by sweir27** [comment]
Ohh cool @orta. It looks like some teams might already have a 1-pager that's an overview that links out to other resources, but would be nice to link to an individual product team's page from our onboarding docs 😄too.

I guess kind of like our template for the READMEs in all of our repos!
