### ISSUE TITLE
Add pre-gravity history to highlights.md

### ISSUE THREAD

**Issue by orta** [artsy/README#196]
e.g. Heroku Bartender, the old gravity etc

https://github.com/artsy/README/blob/master/culture/highlights.md

**Comment by dblock** [comment]
Closed via #204

**Comment by dblock** [comment]
@dblandin I no longer have r/w access here, so pls close for me?

**Comment by zephraph** [comment]
@dblock I gotchu

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
