### ISSUE TITLE
Describe how/when to write post-mortems

### ISSUE THREAD

**Issue by sweir27** [artsy/README#20]
... specifically in the context of the on-call process. When does an #incident turn into a post-mortem-worthy event?

We already have https://github.com/artsy/post_mortems which links to helpful docs but doesn't answer that ☝️question. This could be part of our on-call onboarding docs or something separate.

**Comment by orta** [comment]
This is a debate I'm having right now, two potential rubrics for deciding to write a post-mortem:

- something small which has taken down user-accessible things that has happened multiple times in a row
- something which takes down artsy for longer than 45m

**Comment by dleve123** [comment]
@sweir27 This issue seems to be addressed considering all of the recent training/communications regarding on-call. What do you think about closing, or do you think this is still relevant?
