### ISSUE TITLE
Add doc on ways to grow as an engineer @ Artsy

### ISSUE THREAD

**Issue by sweir27** [artsy/README#21]
For someone interested in stretching in different ways, would be nice to support that with resources/concrete ways of improving.

Growth could be in terms of technology (and we may have docs on this already in README).

Growth could also be in terms of skills that aren't strictly technical. We should have a high-level list of these + links to specific resources for each. Some examples are:
- mentoring
- leadership (management + technical leadership)
- interviewing
- public speaking
- writing

... there are probably more!

**Comment by zephraph** [comment]
We have a [Ladder](https://github.com/artsy/potential/blob/master/team/Ladder.md) describing the different levels of engineering roles. It kinda describes what responsibilities each level has. That would be a good thing to include in the growth section.

**Comment by erikdstock** [comment]
Closing this issue as stale - though we now have generated several of these docs.
