### ISSUE TITLE
[RFC] Document the process for requesting professional development

### ISSUE THREAD

**Issue by iskounen** [artsy/README#210]
## Proposal:

Document the engineering team's process for requesting training, conference attendance, and learning materials.

## Reasoning

We want to have clarity in what types of professional development activities are reimbursed and how to request them. Clarifying this process will hopefully lead to increased requests to pursue opportunities for learning and growing in the engineering team, and a smoother request/approval process for both engineers and their managers.

## How is this RFC resolved?

A playbook document outlining the current process for requesting professional development. This playbook should address questions that engineers and managers have about the process.

**Comment by iskounen** [comment]
Please comment with any questions that you have about the current process 🙌

**Comment by joeyAghion** [comment]
Great idea. Note the existing [conferences playbook](https://github.com/artsy/README/blob/master/playbooks/conferences.md) that could be expanded for this purpose.

I think it would be helpful to clarify:
* criteria for reimbursed trainings/conferences (the playbook mentions "...should be related to the individual's role/growth or Artsy's challenges/technologies" but it may not always be clear).
* and the exact approvals required.

**Comment by ashfurrow** [comment]
👍 from me, echoing Joey's recommendation of expanding the conferences playbook.

**Comment by mdole** [comment]
Big fan of clarifying the process and expanding the playbook! I would find it helpful to have a clearly delineated set of steps, e.g.

### You want to go to a conference! Great!
1. Find out how much the conference costs, including an estimate for any travel
2. Put this information in form XYZ and send it to your manager
3. If your manager gives their stamp of approval, book the tickets
4. Attend conference!
5. In the same month you booked the tickets, use Concur to submit a reimbursement request. Ask your manager for help if you haven't used Concur before or have questions
6. Write up your notes from the conference and share with the team in #slack-channel-that-may-or-may-not-exist

kinda thing

**Comment by ashfurrow** [comment]
@mdole I like point 6 especially – I've started a folder in this repo to collect such conference notes: https://github.com/artsy/README/tree/master/conference-notes

**Comment by iskounen** [comment]
These are great resources, @joeyAghion and @ashfurrow. I'll make sure that the outcome of this RFC expands on existing documentation.

@mdole thanks for getting the ball rolling on a set of steps. I'll add some more details to what you've shared and include that as well.

**Comment by iskounen** [comment]
I've kept this RFC open as a reminder to update the playbook, but since the next steps are clear, I will close it and move to update the playbook.

**Comment by dblandin** [comment]
@iskounen We have a template for resolving an RFC which includes Additional Context and Next Steps. Would you be able to comment again with that template filled out?

https://github.com/artsy/README/blob/master/playbooks/rfcs.md#resolution

**Comment by iskounen** [comment]
Sure thing! I'll update my previous comment to match the template.
