### ISSUE TITLE
Include a list of the banter-y slacks

### ISSUE THREAD

**Issue by orta** [artsy/README#22]
E.g. add these links into [the slack doc](https://artsy.slack.com/archives/C02531TUD/p1533749286000516)

**Comment by ashfurrow** [comment]
We should link to this document from [the engineering on-boarding template](https://github.com/artsy/README/blob/master/.github/ISSUE_TEMPLATE/engineering-onboarding.md). I would be happy to pair on this at writing office hours, too.
