### ISSUE TITLE
Improve software capitalization process

### ISSUE THREAD

**Issue by jonallured** [artsy/README#229]
## Proposal:

I'd like to see us improve the process of software capitalization so that ICs are double-checking their allocations and start/end dates with documentation are added as we go. I'd also like to see us work on this monthly so that we aren't in a rush at the end of a quarter and blocking Rob and his team from closing things out.

Then, once improved we should document the process so that it's easier for new TLs to get up to speed and is a good reminder for existing ones.

## Reasoning

Waiting until the end of the quarter to get Accounting what they need for closing the quarter puts added stress on things - moving to do this continuously where possible and monthly otherwise should spread things out in a way that makes everyone feel super cool.

## Exceptions:

Can't think of any!

## Additional Context:

The current process is documented here:

https://www.notion.so/artsy/Software-Capitalization-22c90e835422423399323b7835f353a3

We'd update that process section, but there's some good context at the top of that doc that's helpful if this is new to you!

## How is this RFC resolved?

Here are the concrete things I'd like to see happen:

### The Software Cap Time by Project Spreadsheet

* Rob creates this sheet at the beginning of the quarter and shares with all of PDDE so that anybody can edit it.

### Monthly Software Capitalization Working Meeting

* A recurring monthly meeting for Rob plus those responsible for filling out the sheet. This is a working meeting to fill out details.
* TLs use Jira (or GitHub or whatever) to take a stab at the percentages of time.
* TLs nudge ICs to review the percentages for a sanity check.

### Regular Team-Specific PDDE meetings

Each team already has a weekly or bi-weekly meeting for the PM, TL, designer and data person to chat. We look at the project board in Notion - let's just take a second to make sure all start/end dates and evidence links are there or assign them if not.

### Documentation

* write up some docs based on this and find a home in README for them

**Comment by sweir27** [comment]
Super into the idea of documenting and iterating on this process!!

**Comment by jonallured** [comment]
Seems like there's no dissent so I'm going to close this as accepted and work on the next steps!! ❤️ 🤗 🎉

**Comment by joeyAghion** [comment]
I'm +1 about opening up the data and creating a built-in opportunity for individuals to fill in or correct their data.

I'm -1 about the new meeting and in favor of async alignment (or just organic communication between PM+TL) if possible. We have a _lot_ of semi-standard meetings and they tend to accumulate.

**Comment by jonallured** [comment]
@joeyAghion that meeting would be optional for all and is more of a placeholder. For me, having an hour on my schedule will mean that I actually do this but if you milage varies, then that's ok too!
