### ISSUE TITLE
Add instructions on how to take a "tour of Artsy"

### ISSUE THREAD

**Issue by sweir27** [artsy/README#23]
cc @xtina-starr for the idea!

One of the items in our onboarding talks about taking some time to tour around Artsy.net in a staging environment, doing things like bidding in an auction and making an inquiry.

It would be cool if we had a doc that outlined some of these and provided some high-level instructions on how to actually do them. 😄

**Comment by dleve123** [comment]
Closed by https://github.com/artsy/README/pull/70
