### ISSUE TITLE
[RFC] Include list of all PR's going out in a release

### ISSUE THREAD

**Issue by mzikherman** [artsy/README#238]
## Proposal:

When there's a PR (from `staging` -> `release`), it would be nice to have a GitHub comment that lists all the PR's included in this deploy. This makes it easier to see what's being deployed, and currently is manual- a deployer looks thru the commits and 'summarizes' what's being deployed.

## Reasoning

The deploy PR itself will naturally list the commits being included, but PR's are more logical groupings of commits for humans to look at. So summarizing the list of commits -> unique list of containing PR's is desirable. 

## Exceptions:

This only works for repos that use the `master` - `staging` - `release` workflow, initiated via GitHub PR's.

## How is this RFC resolved?

A PR to peril-settings adding the check - https://github.com/artsy/peril-settings/pull/133

**Comment by mzikherman** [comment]
Further thought, this can be a GitHub comment and/or **Slack message**?

**Comment by ashfurrow** [comment]
Yeah, seems like a great idea to me 👍

**Comment by zephraph** [comment]
Yep, I like it. Auto generates a list like this and dumps it in the changelog. When a renovate PR comes around that lists the changelog, it's easy to see what PRs were involved. Having our PR release process mirror that feels right. 

👍 from me

You can see how auto does it here: https://github.com/intuit/auto/blob/f148de6f1a146aaa1bd9fd6b048996ea73bbe2e2/packages/core/src/release.ts#L284. @hipstersmoothie set that up originally.

**Comment by mzikherman** [comment]
Resolving! The Peril rule has been merged.
