### ISSUE TITLE
[RFC] Get Sentry Errors to Meaningful State for Our Critical 3 Apps/Services

### ISSUE THREAD

**Issue by ashkan18** [artsy/README#247]
## Proposal:
We need to bring our Sentry errors rate to an acceptable meaningful number for our Critical 3 apps/services and go below our current 500k limit so we can monitor them and properly resolve them and eventually get to 0 event in production (its possible, yes we can!).

### Option 1
On Oct 1st we archive all existing errors for our highest Criticality services/apps on Sentry to get into **"clean state"**. 

From **Oct 1st**, each practice assign a dedicated person during their meeting till next meeting for watching specific critical app/service on Sentry. 

When a new Sentry error happened in one of our **Critically 3** apps one of following actions needs to happen by dedicated person:

- If this error should be caught and not a real bug (missing a catch), in proper service wrap it with proper `try, catch`.
- if this error is real bug and can't be easily fixed in 10mins, open a Jira ticket and add it to backlog of proper product team and let the TL of the team know.
- Resolve the issue in Sentry

### Option 2
Similar as option 1 but slightly less aggressive by handling this on staging.

Every Monday, we clean up Sentry errors on Staging. Each practice assigns a dedicated person for each week to monitor staging sentry for critical apps/services. 

When a new error happens:

- If this error should be caught and not a real bug (missing a catch), in proper service wrap it with proper `try, catch`.
- if this error is real bug and can't be easily fixed in 10mins, open a Jira ticket and add it to backlog of proper product team and let the TL of the team know.
- Resolve the issue in Sentry

## Reasoning

Our Sentry error rate in some of our critical apps is in the level that makes it super hard, if not impossible, to know what errors are real and need to be deal with and whats something thats resolved. 

Benefits of keeping a healthy Sentry error log:
- We can monitor them actively and prevent/detect/resolve incidents sooner
- We can find production errors faster and easier
- We can go below our current 500k event limit and even go to smaller plan (#reduce-burn) (ask @joeyAghion how much we are paying for Sentry)
- No need for bug bash as a one day event

## Exceptions:

none

## Additional Context:

[Some context on slack](https://artsy.slack.com/archives/CA8SANW3W/p1567779228178600)
Example fixing PR https://github.com/artsy/gravity/pull/12577

## How is this RFC resolved?

Deciding between option 1 and 2. Also making sure we don't go above our limits from Nov 1st.

**Comment by ashfurrow** [comment]
I'm a 👍 on this. Option 1️⃣ makes sense to me – why not be aggressive about error-handling? I also dislike the idea of further complicating our weekly staging/production process.

**Comment by ashfurrow** [comment]
Just discussed this with the FE iOS Practice. If we have the Mobile Experience team in place by October 3, ideally this would be something an IC from that team could take on. 

Specifically with iOS, I wanted to bring up something different from our web software. Previous versions of Artsy's app are still being used, even though they might be outdated. [Here](https://sentry.io/organizations/artsynet/issues/587358816/?project=166784) is a crash from this morning generated by a version of our app that we shipped 9 months ago (a fix for the bug has since been shipped, but this user hasn't upgraded to that new version). That's all to say that wiping the slate clean would be particularly valuable for our iOS software (as @kierangillen pointed out) this generates a lot of noise that makes Sentry less helpful.

**Comment by alloy** [comment]
Nice, let’s do it 1️⃣👍

**Comment by starsirius** [comment]
I'm 👍 1️⃣.

I'd also suggest each team to use this opportunity to optimize how we handle errors with Sentry, according to the project's needs. For example, ways to speed up searching for errors, how to proactively alerting errors, maybe we want to use tagging or other Sentry native features, etc.

I'll be very interested in comparing notes and learn from each project in a few months.

**Comment by dleve123** [comment]
Also 👍 on 1️⃣. To be clear, you are only proposing that we "resolve" a record in Sentry once we either app-level suppress it via some form of `try`/`catch` or fix the underlying bug, not after just getting alerted.

**Comment by ashkan18** [comment]
I will add instructions around this, but yes, there is no point to resolve it in Sentry if its not actually fixed/handled properly in the code and will come back again 🙃

**Comment by ashkan18** [comment]
## Resolution
We decided to go with the **option 1** offered by this RFC.

## Level of Support
2: Positive feedback.

#### Additional Context:
People reviewed and read this RFC were all for doing this and in favor of option 1. There were some feedback in how to exercise this option and also how to share our learnings between teams as each team focuses on their project in Sentry.
Some of our projects, like Eigen have more complicated and different release cycles, we need to accommodate and possibly change this clean up considering the project limitations (ex. old versions out in the field) and release cycles.

## Next Steps
- [ ] On **Oct 1st**, we will clean Sentry errors for following projects on production.
  - [ ] MP
  - [ ] Eigen
  - [ ] Force
  - [ ] Gravity
- From **Oct 1st** each practice will need to actively monitor and manage Sentry errors coming in:
  - **Front End**: [Force](https://sentry.io/organizations/artsynet/issues/?project=28316)
  - **Front End iOS**: [Eigen](https://sentry.io/organizations/artsynet/issues/?project=166784)
  - **Platform**: [Gravity](https://sentry.io/organizations/artsynet/issues/?project=157936) + [MP](https://sentry.io/organizations/artsynet/issues/?project=299996)
- Each practice can create their own slack channel for monitoring sentry errors coming in for this channel. Whoever is looking at specific sentry error can tag that on slack with 👋 emoji to avoid duplicate attempts of fixing something. (*optional)
- A Sentry issue can be resolved if:
  - A PR is opened to fix the issue.
  - A PR is opened to properly catch the error and log it. When opening PR make sure:
     - label the PR with `sentry-fix` label.
     - Point to the url of the issue in Sentry. (example PR: https://github.com/artsy/gravity/pull/12577)
- A Sentry issue can be ignored on Sentry if:
   - This error could totally be ignored (its an older iOS version)
   - Error was caused by other one time spikes or service unavailability.
#### Exceptions
A Sentry issue can be leave as is if the person looking at it could not possibly fix the issue in ~10 minutes and the error seems more involved. In this case we should create a Jira ticket in proper product board and notify TL and MP about it.
