### ISSUE TITLE
[RFC] Feedback Friday

### ISSUE THREAD

**Issue by sweir27** [artsy/README#248]
## Proposal:

Every other Friday (the last Friday of the sprint), all of PDDE sets aside 30 min for quiet desk-time that we use to give our team members and peers feedback related to the prior sprint.

During this time, team members are encouraged to:
1. Message the `@Lattice` app with the command `request` and explicitly _request_ feedback from one other member of their team.
2. Message the `@Lattice` app with the command `feedback` to _give_ feedback to one or more members of the team (whether requested or not).

Notes:
- Requesting feedback should not take more than 2-5 minutes. An example of a request prompt is:
 > I'm interested in hearing about how I was as a pairing partner on the exploding widgets project. This was my first time "driving" and I'm curious how that went/how I can do a better job next time.
- Feedback for an individual should not take more than 5-10 minutes-- make it short! It's meant to be scoped to the prior sprint. Consider giving both positive and constructive feedback. An example is:
> This sprint Betty did a great job on her tasks to add exploding widgets to the homepage. She had to dig deep into code that hasn't been touched for years and while she was there she made some crucial refactors that will make it easier for us all to develop in the future. It's always such a joy to touch code that Betty has written!

> I noticed that Betty was late to a couple of meetings this sprint, which made it hard for us to get started on time since we weren't sure when she was arriving. If Betty can't make it to a meeting, it would be great if she could let us know in slack so we don't wait up!

- The goal is for all of us to stretch our feedback muscles and help each other grow.
- We should certainly iterate on this process! This is just an initial idea based on a few attempts on the purchase team.

## Reasoning

One of the main takeaways from our last climate survey was that we wanted more constructive feedback from our peers. This is an attempt to address that need.

Having a healthy feedback culture also relates back to many of our Artsy values, including Openness and People are Paramount. It's why we spend so much time giving thoughtful feedback during performance reviews time! However, our current feedback mechanisms (PR reviews, performance feedback, retros), don't necessarily encourage continuous, in-the-moment feedback that can help us grow outside of the performance review cycle. 

The process proposed is intended to be _light_ and _frequent_ and stretch our feedback muscles over time. Hopefully it becomes second nature the more we do it.

## Exceptions:

There's no way to fail at this-- if you can only think of props for someone, give those! If you can't think of any feedback to give to a member of your immediate team, give some to someone else! The structure provided is just a guideline to help us all practice this skill, but we should feel free to adopt it in the way that feels best.

## How is this RFC resolved?

- A calendar event is created (all of PDDE invited) for 30 min every other Friday (end of the sprint), with the proposed structure included as an event description. We could additionally add slack reminders to each team's channel.

**Comment by mdole** [comment]
Really big fan of this idea. Consistent, regular feedback will both result in more growth for individual engineers and in a better experience at performance reviews when we have lots of feedback from different people to look back on.

**Comment by zephraph** [comment]
I love this. One of the things that I mentioned about our yearly review process is even though we have feedback training before hand, it still felt awkward and cumbersome because _I_ wasn't practiced at giving (or receiving) regular, continual feedback. 

Thanks @sweir27!

**Comment by damassi** [comment]
How might this may overlap with Retros?

**Comment by sweir27** [comment]
@damassi Good question! This feels separate from retros as it's more about giving actionable feedback directly to peers whereas retros tend to be about improving team function. So they both feel necessary for different reasons. Does that resonate?

**Comment by damassi** [comment]
It does! 

How might this overlap with weekly props? Because it seems like there might be some overlap there and either a) increase time spent giving props on Monday (since team members have thought about it on Friday); or b) decrease props (since it's already been said directly.

Also, is anyone open to discussing the cadence of Feedback Fridays? `52 feedback sessions * x number of team members` seems like it could pretty quickly turn into micro management, overanalysis, or superficiality due to sheer volume of requests. Tying this to our Sprint cycles or perhaps making it monthly seems a bit more healthy.

**Comment by sweir27** [comment]
Ah! Good question about Monday props, hadn't thought of that.

And good call-- I was inconsistent with my intro vs. the `resolved` section. That's supposed to be _every other Friday_ to correspond with the ending of a sprint!

**Comment by damassi** [comment]
👌perfect.

**Comment by damassi** [comment]
One more comment: Cycles of regular feedback like this (at team scale) seems like it could surface some stuff (for the better or worse), similar to how things work when one is in therapy... It might be worth thinking through official-channel conflict resolution should it be needed.

**Comment by dblandin** [comment]
I really love this idea and have admired your team's habit thus far. Would love to see this reach all of PDDE! :heart:

**Comment by joeyAghion** [comment]
Intellectually, I really think more frequent, lighter-weight opportunities for timely feedback could help our whole engineering org improve.

That said, we haven't adopted this in Platform yet and I'm wondering why. Feedback is [always] hard and scary. We have so many meetings and struggle to coordinate basic things that I don't look forward to another calendar item. On the other hand, it's just 30 minutes and we can be "optional" attendees.

Overall I think this could have a positive effect of lowering the threshold for offering feedback and increasing the expectation and peer-pressure. (Seriously, I think many of us _would not_ proactively offer minor feedback unsolicited, but if many of those around us are participating it starts to feel possible.)

**Comment by joeyAghion** [comment]
Thought: is there any reason this has to align with the end of a sprint? For individuals on teams who like to be head-down on delivery work most of the time, the end of the sprint probably already feels like a huge process pile-up. Maybe it can be every other week timed to _alternate_ with the ends of sprints?

**Comment by ashfurrow** [comment]
@joeyAghion that makes sense! We've been tying it to the sprint because, often, we decide pairs of people to work on things together. These pairs collaborate over the course of the sprint, and I think the desire here was to capture feedback from a sprint's worth of collaboration. But given the additional process pile-up this could introduce, I would personally be fine with moving to whatever schedule works for us.

However, I think we should stick to a 2-week cadence. This is supposed to be lightweight and get us in the habit of giving frequent, small pieces of feedback. A longer cadence runs the risk of feeling too onerous, in my opinion.

**Comment by dleve123** [comment]
I think this is awesome 👍. As someone that can prefer to give feedback in-person/real-time, I think we should leave the format open (but with a preference towards lattice as it is easier for managers to get signal that way), but introducing regular feedback as part of the culture is great.

**Comment by ashfurrow** [comment]
@dleve123 The value of using Lattice comes when it's 360º review time; having a history of all the feedback someone has gotten makes it a lot easier to see how they've grown and where they should focus on next. In-person feedback sounds awesome, but maybe it could be recorded later in Lattice for posterity?

**Comment by dleve123** [comment]
> having a history of all the feedback someone has gotten makes it a lot easier to see how they've grown and where they should focus on next. In-person feedback sounds awesome, but maybe it could be recorded later in Lattice for posterity?

Yup agreed. I, at least personally, can commit to that!

**Comment by sweir27** [comment]
Thank you for all of the comments! I'd like to close this with some next steps:
- I will create an optional event for PDDE for every other Friday. I'd like to start with the end of the sprint for now (per @ashfurrow's comment about how that tends to align with some completion of shared work), but this can easily change!
- The calendar invite will serve as reminder but, like I mentioned, teams should feel free to change the timing! Hopefully we can all share knowledge about what's working best for each of us and adjust over time.

**Comment by kazemaks** [comment]
@sweir27 does `@Lattice` really work now? I couldn'r reach my artsy account under https://artsy.latticehq.com and an app I found in Slack didn't respond to the `/request` command. Can you guide me thru this a lil bit so I could transfer this info to iTA colleagues?
