### ISSUE TITLE
[RFC] Proposal to add "Context" and "Stakeholders" to technical plan documents.

### ISSUE THREAD

**Issue by mbilokonsky** [artsy/README#259]
## Proposal:

In addition to **Motivation**, **Impact**, **Approaches**, **Risk**, **Decisions** and **Outcome** I'd like to suggest that we add **Context** and **Stakeholders** to our technical plan templates. These would both go at the end of the document, and can be considered sort of ancillary metadata if we want.

**Context** is a section where relevant links, explanations and background can go without breaking the flow of the core document above. Think of it as, like, a space to put footnotes.

**Stakeholders** is a specific list of individuals who sign off on the decisions presented by the document in order to move forward.

## Reasoning

Technical plans need to be concise and understandable, but sometimes decisions don't make sense without a lot of context. Given our current model I have to stick a lot into "motivation", for instance, that isn't _actually_ about motivation but rather an explanation of how stuff works right now. So providing an explicit space for structured citations, documentation and simply relevant storytelling feels like something that could help us to streamline these documents while also allowing us to provide more information.

Re: Stakeholders - something that's not always clear to me is how and when decisions actually get made. Right now I've got an open technical plan, and I'm working with my team on it, soliciting org feedback, etc - but it's not clear to me how I will know when we're done with the technical planning and ready to begin development.

Adding stakeholders as individuals who have to sign off on decisions made is one way to address this challenge. I envision using this not just to, like, tag my team lead and project manager and let them decide when it's done - I want to tag people on other teams or in other departments whose work will be impacted by the decision, and I want to make sure that they feel like their feedback was considered as well.

Creating a space for stakeholders to explicitly register that they're aware of the current plan and approve of the decisions made is a great way to ensure that People are Paramount here at Artsy while distributing institutional knowledge across the company. 

## Exceptions:

Not every technical plan requires a lot of context. Not every technical plan requires stakeholders. But sometimes, especially when the proposed work cuts across a number of domains at once, it can be helpful to have the reminder that we should be seeking to actively include anyone whose lives we may be making better or worse through our decisions. :)

## Additional Context:

Plus then we could start referring to our technical plans as MIARDOCS and I think that's pretty cool!

## How is this RFC resolved?

We add the two fields to our technical plan template in Notion.

**Comment by mdole** [comment]
@mbilokonsky I dig! What would you think about specifying a `DRI` instead of `Stakeholders`? Seems to me like that might create even more clarity around who's in charge of moving the project forward and resolving questions.

**Comment by mbilokonsky** [comment]
So, Stakeholders here is meant to be the opposite of a DRI, kind of. It's a list of people whose opinions we have to make sure we collect because it would be easy to forget about e.g. non-technical stakeholders or e.g. work that's actually coming from a working group and made its way to us.

Just the idea that "there are people whose lives will be impacted by this change and we need to make sure we collaborate with them as we make it", sort of?

**Comment by mdole** [comment]
makes sense! stakeholders it is!

**Comment by zephraph** [comment]
>  Given our current model I have to stick a lot into "motivation", for instance, that isn't actually about motivation but rather an explanation of how stuff works right now.

I feel like this means that `Motivation` is a bad header title for the first section. Often times, there's already a product brief that covers a lot of the `why` of the technical doc. That first section is sort of intended to capture a lot of context. I'm not convinced that both `Motivation` and `Context` should exist, but I am on-board with working on the naming.

**Comment by mbilokonsky** [comment]
I've gone through and updated all of the [RFC templates here](https://www.notion.so/artsy/Technical-Plans-f94b206fcec54cee8b4d864e67d5b70f) to add these two fields, thank you everyone who chimed in!
