### ISSUE TITLE
RFC: Install graphql-inspector on metaphysics

### ISSUE THREAD

**Issue by zephraph** [artsy/README#268]
## Proposal:

[Graphql Inspector](https://graphql-inspector.com/docs/recipes/github) is a cli tool and GitHub app that provides utilities for detecting breaking schema changes (among other things).

I'd like to install the GraphQL Inspector GitHub app which would use the checks api to highlight any breaking changes in the schema (as in the image below). 

![image](https://user-images.githubusercontent.com/3087225/68875165-5c510800-06d0-11ea-9546-577ab1c03891.png)

Breaking changes to the schema would mark the PR status as red. That doesn't mean we couldn't still merge, but we'd definitely have to be more intentional (which is a good thing in my opinion). 

## Reasoning

It's relatively easy to make breaking changes to a schema. This would make it glaringly obvious that we made a breaking change and hopefully _discourage_ future breaking changes. 

## How is this RFC resolved?

The GitHub app is installed _or_ we add the GitHub action to metaphysics.

**Comment by ashfurrow** [comment]
Makes a lot of sense to me!

**Comment by alloy** [comment]
The pricing isn’t really clear to me and also I seem to recall that the GH plan we’re on might impact our ability to use apps [long-term], but perhaps I’m wrong?

**Comment by zephraph** [comment]
It's free. Also, open source so we could self host. If we go the actions route, that's also free for open source. 

There's no limitation on any pricing plan that I'm aware of that limits the number of apps you can use.

**Comment by damassi** [comment]
@zephraph - Would this be covered by the Apollo tooling platform work that's WIP?

**Comment by zephraph** [comment]
Very likely, yes. Here's a note from their [docs](https://www.apollographql.com/docs/intro/platform/#schema-change-validation). 

Their pricing model has changed so I'm not sure if it'll work out for us to go with their full platform though. We'll have to do some evaluating when we get there. 

In the mean time this is a simple enough thing to add (and remove).

**Comment by damassi** [comment]
cc @joeyAghion
