### ISSUE TITLE
Using Artsy/readme concept for our dev team

### ISSUE THREAD

**Issue by tonymrakovcic** [artsy/README#269]
Hello!

My name is Tony and I am head of development at Bornfight, a Croatian Software company.

I am reaching out to you because I am absolutely inspired with the artsy/README repo, and plan to do the same for our company (bornfight.com, github.com/bornfight).  I would just like to check with you if this is ok :)
We plan to link and give full credit of course, for the ideas, implementation, and the fact that it is basically an edited copy of your idea.
The open source by default philosophy for me personally is mind blowing and I think the approach is something that has so many benefits that promote great team culture.
Are there any specific things we would have to give extra thought? Maybe licences or similar?
We plan to use the structure generating script, and maybe the tech radar in the future. The content would naturally be our own.

Thank you very much.

**Comment by ashfurrow** [comment]
Hi @tonymrakovcic! Thanks for the thoughtful question. You're more than welcome to use this kind of format – we ourselves discovered it elsewhere, too! We've got [a blog post](https://artsy.github.io/blog/2018/08/21/OSS-by-Default-Docs/) that goes over the thinking process behind this repo, which cites [Buffer's README repo](https://github.com/bufferapp/readme) as inspiration. 

Please let us know if we can clarify anything else.

**Comment by dleve123** [comment]
Closing as I believe this conversation is resolved.
