### ISSUE TITLE
Make a technology roadmap that includes front-end needs

### ISSUE THREAD

**Issue by orta** [artsy/README#3]
Right now, this lives in platform: [`practices/platform/technology-roadmap.md`](https://github.com/artsy/README/blob/038f56adb11633ef635eada969ca1c62193fefb4/practices/platform/technology-roadmap.md) - but ideally it is scoped to all teams.

**Comment by dleve123** [comment]
Our [technology radar](https://github.com/artsy/README/blob/master/playbooks/technology_radar/artsy-tech-radar.csv) includes front-end needs. Closing for now as I don't think this has been addressed! (feel free to re-open if ya disagree @orta)

https://radar.thoughtworks.com/?sheetId=https%3A%2F%2Fraw.githubusercontent.com%2Fartsy%2Freadme%2Fmaster%2Fplaybooks%2Ftechnology_radar%2Fartsy-tech-radar.csv
