### ISSUE TITLE
RFC: All GraphQL API servers have a root `_schema.graphql` file

### ISSUE THREAD

**Issue by orta** [artsy/README#31]
## Proposal:

[Metaphysics](https://github.com/artsy/metaphysics#metaphysics-), [Exchange](https://github.com/artsy/exchange/), [Convection](https://github.com/artsy/convection) and [Gravity](https://github.com/artsy/gravity) (for GravQL) and (any others I can't think of all, impulse/pulse?) have a `_schema.graphql ` file in the root of their respective repos. We add a pre-commit hook that ensures the schema is always up-to-date.

## Reasoning

Mainly to move PR review up a level of abstraction to easily discuss schema design, secondary to improve tooling.

1. Doing this means that people can see directly in the PR, in a language agnostic way, the changes to an API schema
1. `_schema.graphql ` is a weird name yes, but I want it to be at the top of the PR every time.
1. Having this file means that we can build consistent tooling around all the repos. Without thinking too deeply:
    - Metaphysics stitching updates can be scripted in MP
    - Client schema updates can be trivially scripted too
    - Peril can poke #graphql when there are schema changes in any repo (easing comms burden on folks)
    - Peril can offer weekly changelogs of all schemas
    - We can build cross-language linter rules like "please always use unions in mutation"

## Exceptions:

Nothing I can think of? Probably worth adding a CI check though incase people decide to skip the 

## Additional Context:

A hat-tip to @cjoudrey who brought this idea up and discussed its merits within GitHub's API at the NYC GraphQL meetup.

**Comment by orta** [comment]
> You may want to use the .graphql extension in order to obtain syntax highlighting in GitHub and in editors. Maybe _schema.graphql?

Thanks, updated!

**Comment by ashkan18** [comment]
Nice! 👍 do you have an example PR that includes this? I can update Exchange with this.

**Comment by orta** [comment]
## Resolution
We decided to do it.

## Level of Support
2: Positive feedback.

#### Additional Context:
I think for Metaphysics we may still need to keep the JSON version around for our ruby apps, (see 
https://github.com/github/graphql-client/issues/16 )9 but we can use [.gitattributes](https://github.com/artsy/emission/blob/master/.gitattributes) to ignore those in PRs.

## Next Steps
I'll add this to metaphysics this week, and add it to all the other projects using GraphQL next week ideally.

#### Exceptions
None that I know of.

**Comment by orta** [comment]
This is shipped in Metaphysics with https://github.com/artsy/metaphysics/commit/dd8b014f04c76e11eddff4af239e4f256ea64415
