### ISSUE TITLE
Deprecate React Storybooks feature from Force

### ISSUE THREAD

**Issue by eessex** [artsy/README#334]
## Proposal:
Remove React Storybook features, tooling and libraries from Force.

## Reasoning

When we added storybooks to our development process, it was in the context of Reaction used as a component library-- meaning we developed components without the context of an app/server.  Our process has evolved multiple times over since, and now that component development happens in Palette and Force, it is unclear if the Storybook features are either valued or used by engineers. 

Cons:
- Changes to Storybooks in Force take around 30 seconds to load, making them difficult to develop against
- Dependencies and files take up space on our production Docker image, at least ~ 300MB
- We are no longer deploying a static site to host storybooks on the public internet, so non-developers are definitely unable to access

## Exceptions:

N/A

## Additional Context:

This was raised in the Front-end channel for discussion, but I wanted to raise visibility to ensure there are no conflicting opinions, and that this is not an interruption to development workflows.

You can see our discussion [in slack here](https://artsy.slack.com/archives/C02BC3HEJ/p1601577411114100)

## How is this RFC resolved?

PR removing all `__stories__` directories, related code, and libraries from Force.

**Comment by damassi** [comment]
While I'm in favor

> Changes to Storybooks in Force take around 30 seconds to load, making them difficult to develop against

isn't a problem with storybooks, but rather an issue with our tooling that needs to be addressed but hasn't had dedicated dev resources to do so.

**Comment by ashfurrow** [comment]
Yeah, I'm not partial to removing or keeping them but I think it's fair to make Chris' distinction. Dependencies taking up space in our production Docker image _also_ seems like something we could fix (I think?). Those are both still valid reasons for removing Storybooks as long as they aren't being used that much by developers. But if they _are_ useful, then I think we could talk about fixing the DX instead of removing them.

**Comment by erikdstock** [comment]
I haven't used storybooks with force in a very long time. In general, while I've found it nice for rapid development at times, the friction involved in maintaining another specific development setup is high enough that I'd rather just use the various other development tools I have at my disposal. I am a :+1:.

**Comment by eessex** [comment]
## Resolution
We will move forward with deprecating this feature

## Level of Support
3: Majority acceptance, with conflicting feedback.

#### Additional Context:
Neglecting upkeep of our storybooks configuration is the larger issue than any size issues it brings to our schema, but because we've seen no examples of developers using this in recent memory it doesn't seem worthwhile to put developer time into reinstating this feature to a functional state. 

## Next Steps
- Remove `__stories__` folders from Force
- Remove storybooks-related libraries from force
