### ISSUE TITLE
RFC: Formalize Practices artifacts and communication channels to increase participation

### ISSUE THREAD

**Issue by SamRozen** [artsy/README#349]
## Proposal:

As our engineering org keeps growing and we rely more and more heavily on practices for cross pollination and normalization across teams, I'd like to suggest more formal expectations around practices management:

Each practice should have:
- A public slack channel named practice-X (i.e. practice-platform, practice-data)
- A public google group names X-practice that is open and that anyone can join
- For practice meeting, calendar invites should go to the corresponding google group (so that anyone can add themselves) and to the engineering open calendar.
- A practice lead who is responsible for scheduling and facilitating the meetings, curating the agenda, report back key takeaways outside the practice, be the first point of contact for questions regarding the practice.
- A Notion page linked from [here](https://www.notion.so/artsy/Practices-f5b3d4150c804421b2db407649947797)🔒 that captures all the points above + meeting notes.

## Reasoning

Unless one is actively participating in a practice, it is difficult today to have visibility into (and be able to chime in) ongoing practice related conversations or know who to talk to. 
Some practice conversations are happening in specific team channels (data, platform) which can also create a higher barrier to entry. 
This hasn't been an issue in the past with long standing practices (platform, front-end & iOS) but now that we're bootstrapping new practices (like the data practice) and new people are joining at an increasing pace, more standard conventions will help increase adoption and participation.
It can also be helpful for other folks outside of engineering (like PM, Data & Design) to have more context around what's happening at the practice level and even participate more actively when need be.

## Exceptions:

None. This would currently apply to the front-end, mobile, platform and data practices and any newly created practices.

## How is this RFC resolved?

- Current practice leads are on board with this proposal.
- Slack channels & email groups are created & updated.
- Notion pages are up to date.

**Comment by joeyAghion** [comment]
Seems like a nice opportunity for a little consistency to lower barriers and increase cross-pollination.

I want to highlight one thing:

> A practice lead who is responsible for... reporting back key takeaways outside the practice...

Despite taking extensive notes, we don't do this^ enough. Light-weight reports (in slack) would allow an even bigger audience to stay aware of topics without a big time investment.

**Comment by SamRozen** [comment]
## Resolution
We decided to do it. New slack channels and google groups now exist.

## Level of Support
1: Overwhelming positive feedback.
