### ISSUE TITLE
RFC: Slight Rebranding for Artsy Engineering

### ISSUE THREAD

**Issue by jonallured** [artsy/README#364]
Update: I did some research and we actually already have artsy.engineering booked, we just don't have it going anywhere.

## Proposal:

I would like to make the following changes:

* register and use the URL artsy.engineering for our blog rather than artsy.github.io
* update our Twitter handle from `ArtsyOpenSource` to `ArtsyEng`
  * adjust the name from `Artsy Open Source` to `Artsy Engineering`

## Reasoning

By using the url artsy.github.io we tie ourselves to the GitHub pages-generated site so it becomes awkward to change the tech that powers our blog. Note this RFC is **not** about changing this tech, I simply want to make a move that makes it possible.

So if we're going to make that move (use artsy.engineering as our blog url), then I think `ArtsyEng/Artsy Engineering` are more clear names than `ArtsyOpenSource/Artsy Open Source` for Twitter. This is more opinion than anything else, but I like the simplicity of `Artsy Engineering` overall. It also fits better with `Artsy Engineering Radio`.

## Exceptions:

None but I'll note that my intention would be to redirect traffic from artsy.github.io to the new url.

## Additional Context:

I don't have much context about some of these choices - it's possible the choices made were intentional but it's also possible they were sorta arbitrary.

## How is this RFC resolved?

* register the suggested domain
* add DNS records to point it at GitHub Pages
* update GitHub Pages config to accept the traffic
* ensure traffic to artsy.github.io redirects to the new url
* go into Twitter settings and update the name/handle of the account

**Comment by pepopowitz** [comment]
1. I generally love the idea. I'd much rather have our own URL than github's. 
2. I'm concerned about the optics of changing away from Open Source. 
3. Would this include changing the `opensource@artsy.net` email address we share externally?

**Comment by joeyAghion** [comment]
History: The Github association was definitely intentional. I think it was in the spirit of [Github is your new resume](https://code.dblock.org/2011/07/14/github-is-your-new-resume.html) (as in, it should be our engineering team's resume too).

A rename makes sense to me, if only because the site's content is about Artsy engineering more than exclusively open source projects. (I _think_ the same applies to the twitter handle, assuming we haven't used it to tout new OSS releases much.) "Engineering" is also right there in the header, while Github is only in the domain. Also, controlling the domain is important in the long term.

* Like @pepopowitz, I'm a little concerned about the optics. Either way, we should keep the excellent [and prominent] Open Source page, and maybe even update it.
* How would this affect pages' Google rank? (This is actually pretty important!) Last I checked, there wasn't an SEO-friendly way to `301`-redirect from Github pages. Maybe canonical tags?

**Comment by zephraph** [comment]
A note: I bought `artsy.dev` (it's pretty cheap) with a similar thought in mind. Happy to transfer that over if folks want to use it.

**Comment by mdole** [comment]
I'm pro-URL change, and I think `artsy.dev` might even be a bit nicer than `artsy.engineering` just since `.engineering` is a pretty uncommon top-level domain.

While I agree with what Joey and Steve said about the optics of changing away from "Artsy Open Source" being not great, I think Artsy Engineering more accurately reflects what we are. We are an engineering team, not an open source group/organization/thing. And while much of our work is still in the open, my feeling is that open source is not as much of a focus for our team as it used to be. 

I think we could work on changing that and re-prioritizing open-source contributions if we want to, but my personal experience has been that we're not actively contributing to open source outside of Artsy's open repos _as a team_. We have individuals making contributions, definitely, but it's not something I see a lot of folks spending work time on.

**Comment by annacarey** [comment]
My two cents is that changing to Artsy Engineering is a lot more clear and representative of the current state of the team, our work, and what we plan to share on the blog, podcast, etc. It might be a good opportunity to write up a super-short post about why we're making the change, why and how Open Source continues to be a core value of our team (w/ examples), and an overview of the goals and plans for our content strategy going forward. Maybe this type of documentation already exists, but if not, it would be a good opportunity to write something up about our future plans, how the channels fit together, and our "why" behind it all. @pepopowitz happy to work with you and others if this hasn't already been done!

**Comment by The-Beez-Kneez** [comment]
I think the switch to `artsy.dev` is a positive change. Dev holds the connotation for more than just engineering, so it can imply things such as culture, best practices, etc and not just engineering nuts and bolts. This could also be a nice chance to formally update and announce missions and tenants. If people are concerned that we are not upfront with a desire to keep "Open Source" prevalent throughout, then a section on our goals/missions would be the perfect spot to outline such commitments.

Would also be interested in helping with all of this in any capacity @jonallured

**Comment by damassi** [comment]
+1 `artsy.dev`! 

I do wonder how Open Source centric we still are since Orta, Ash and DB left. This is a separate discussion, however.

**Comment by dblandin** [comment]
Also in favor of a switch to `artsy.dev`!

**Redirects**

> Last I checked, there wasn't an SEO-friendly way to 301-redirect from Github pages. Maybe canonical tags? - joey

Looks like redirect support _away_ from GitHub pages can get a bit clunky but possible with some meta/link tags:

```html
<!DOCTYPE html>
<meta charset="utf-8">
<title>Redirecting to https://artsy.dev</title>
<meta http-equiv="refresh" content="0; URL=https://artsy.dev">
<link rel="canonical" href="https://artsy.dev">
```

soure: https://dev.to/steveblue/setup-a-redirect-on-github-pages-1ok7

**Rebranding blog post**

> It might be a good opportunity to write up a super-short post about why we're making the change, why and how Open Source continues to be a core value of our team (w/ examples), and an overview of the goals and plans for our content strategy going forward. - anna

> This could also be a nice chance to formally update and announce missions and tenants. If people are concerned that we are not upfront with a desire to keep "Open Source" prevalent throughout, then a section on our goals/missions would be the perfect spot to outline such commitments. - AL

+1 to the above points! I think we might also consider coordinating the rebranding actions (putting the redirect in place / renaming the twitter account) with a new blog post that we can point to right away. Would be a great opportunity to redefine what open source means to the team and refresh our goals.

**Comment by SamRozen** [comment]
👍  supportive of the change of domain and being transparent about why we're rebranding.

**Comment by dblandin** [comment]
Just thought of our YouTube channel, which is also called "Artsy Open Source": https://www.youtube.com/channel/UCS5LPLfg8jyA6g3qQs7vt3A

Would this rebranding also affect that account?

**Comment by jonallured** [comment]
Thanks all for the great feedback! It appears there's generally support for this idea but I wanted to follow up on some of the details brought up.

## The Domain Name

I don't think `.engineering` is that uncommon, but agree that `.dev` is better and I know a guy. ;)

I'll also point out that Shopify does a pretty cool thing where they have both:

* https://shopify.engineering/ - their main engineering site, including blog
* http://shopify.github.io/ - an index of all their open source projects

This could be a cool way of handling it!

## The Twitter Handle

No dissent about using `ArtsyEng` so seems like we're good with that.

## Optics of Name Change

I beleive the culture of open source at Artsy is strong and will not be affected by a name change but I also _love_ the suggestions to reinforce this! At a minimum it would make sense to me for us to produce a blog post explaining the change. Maybe a podcast episode too!

## SEO Implications

I spoke with @jpoczik about the SEO implications and she was not concerned. We did some research and have some ideas about how we'll ensure the blog doesn't suffer as we move to a new domain. Especially if we keep the GH page version as an index of our OSS work.

## Miscellaneous

* opensource@artsy.net - I don't know where/how this is shared or used so I'm not sure what to say about it. Seems like we could do nothing and probably be fine? We have other, more general addresses like dev@artsymail.com.

* [Artsy's YouTube channel][ayc] - Seems like we should just update the name to Artsy Engineering to match. Open to other ideas if people have strong opinions.

## Next Steps

* begin prepping a blog post about this change - work with @annacarey
* get artsy.dev - work with @zephraph

Anything else I missed?

[ayc]: https://www.youtube.com/channel/UCS5LPLfg8jyA6g3qQs7vt3A

**Comment by annacarey** [comment]
@jonallured WOOH thanks for synthesizing so beautifully! Maybe we should set a (loose-ish) timeline/deadline for this, so we have a reason to get moving on these changes?

**Comment by joeyAghion** [comment]
> ...have some ideas about how we'll ensure the blog doesn't suffer as we move to a new domain

Can you expand on this? I think it's possibly the most risky issue, given the ~15K monthly visits and the pleasant tailwind that provides to our recruiting.

**Comment by jonallured** [comment]
Reporting back on the SEO stuff! The blog is setup in Google Search Console with two properties:

* `http://artsy.github.io` - this has been setup for some time
* `https://artsy.github.io` - I just set this up today

And here's an alarming chart:

<img width="918" alt="Screen Shot 2021-02-25 at 4 14 20 PM" src="https://user-images.githubusercontent.com/79799/109226545-8c68d100-7784-11eb-8d42-af9df65c719c.png">

This is from the first of those two properties.

So what I believe this is telling us is that around 1/8 or so a change was made that caused the http version of the blog to no longer be indexed. I expect that I'll see those indexed pages show up in the https version.

If this is true, then I think I'll follow the same idea for moving to a new domain

* create a new property in GSC for https://www.artsy.dev
* add canonical links from https://artsy.github.io to https://www.artsy.dev
* check to see that the indexed pages move from one property to the other

Does that address your concerns @joeyAghion?

**Comment by joeyAghion** [comment]
I don't know. 😞 

Would hosting canonical tags on artsy.github.io pages pointing to www.artsy.dev require that both sites be operating for some period of time, until we can hopefully start redirecting from the older one?

**Comment by jonallured** [comment]
> both sites be operating for some period of time

Yes, this is my assumption. I'm going to do a test to ensure that a GitHub Pages site configured with a CNAME also resolves on the github.io domain. I think it will and if so then we can migrate over time rather than switching with our fingers crossed, haha. Either way I'm going to close this sucker as accepted and now we're just discussing approaches.

**Comment by dblandin** [comment]
@jonallured When you have a moment, can we follow up with the resolution template here?

https://github.com/artsy/README/blob/master/playbooks/rfcs.md#resolution
