### ISSUE TITLE
RFC: Retire PDDE OOO Calendar in favour of Bamboo

### ISSUE THREAD

**Issue by admbtlr** [artsy/README#383]
## Proposal:

It's possible to get an iCal feed of people's time off directly from Bamboo. We should therefore retire the PDDE OOO calendar.

## Reasoning

If everybody uses the Bamboo calendars to show "Who's Out", we no longer need the PDDE OOO calendar. This will remove one step in the process of taking time off.

## Exceptions:

None

## Additional Context:

To create a new iCal feed:

1. Click on `Full calendar` on Bamboo (you need to mouse over the Who's Out sidebar to see the link)
![image](https://user-images.githubusercontent.com/1815204/114401776-86e41080-9ba3-11eb-82e5-a9a0d84ae06c.png)

2. Select `iCal Feeds...` from the dropdown in the calendar view
![image](https://user-images.githubusercontent.com/1815204/114402069-c6aaf800-9ba3-11eb-8716-b47aed71709e.png)

3. Copy the link for the `Who's Out` calendar
![image](https://user-images.githubusercontent.com/1815204/114416235-c36a3900-9bb0-11eb-8d6f-4216b1b6f5b9.png)

## How is this RFC resolved?

We delete the PDDE OOO calendar.

**Comment by SamRozen** [comment]
+1 ! This will be a great incentive to use Bamboo more. Also, being more diligent about tracking time off will help us support risk of burnout as we can identify more easily people who haven't taken any break or been able to recharge for too long.

**Comment by sweir27** [comment]
Nice! Excited to consolidate.

Couple of thoughts/questions:
- It looks like this will pull in the Artsy-wide OOO calendar (vs. just scoped to PDDE). That could get a little noisy, which I think is why we added the PDDE-specific originally. Is it possible for us to get a feed of _just_ PDDE? (Maybe a question for people ops)
- Would be worth including these calendar setup instructions _somewhere_... (struggling to think of the best place at the moment).
- Let's make sure to share this with all of PDDE as it'll affect non-E teams as well.

**Comment by admbtlr** [comment]
> It looks like this will pull in the Artsy-wide OOO calendar (vs. just scoped to PDDE). That could get a little noisy, which I think is why we added the PDDE-specific originally. Is it possible for us to get a feed of just PDDE? (Maybe a question for people ops)

Oh, that's interesting - when I did it, I just got PDDE. Maybe it depends on whether you have a filter set in the calendar view?

I'm actually also a little confused about whether these iCal feeds are directly related to a particular user. It seems like you can just keep regenerating them at will. I guess I should clarify that before we move forward.

**Comment by ashleyjelks** [comment]
Would we also use Bamboo to track hourly OOO time, e.g. being OOO for 2 hours for a dental appointment? I personally find it quite convenient to add blocks of OOO time to my personal calendar (and then to copy it over to the PDDE OOO one) and also to check the PDDE OOO cal when I'm looking to schedule a meeting with someone. This now introduces an additional step of logging into yet another workflow (Lattice, Greenhouse, EverFi, Looker, now Bamboo, et. al)

**Comment by admbtlr** [comment]
That's a good point @ashleyjelks. I don't think you can get more granular than a day in Bamboo. But I'm also not sure whether it's necessary to add dental appointments to a global calendar - if I want to set up a meeting with you, I'll check your calendar to see when you're free; as long as you have your dental appointment on your own calendar, that should be fine. Does that sound reasonable?

**Comment by ashleyjelks** [comment]
@admbtlr definitely!

**Comment by joeyAghion** [comment]
I was able to select "My Circle" from the calendar drop-down between steps 1 and 2 to generate a more tailored calendar feed:

<img width="506" alt="Screen Shot 2021-04-19 at 12 28 14 PM" src="https://user-images.githubusercontent.com/28120/115271114-fe1d2580-a10a-11eb-8ced-5b16ec723a77.png">

**Comment by sweir27** [comment]
Oh awesome!! That alleviates my concerns-- we should make sure to call that out in the relevant playbook.

**Comment by jonallured** [comment]
Hey @admbtlr I'm not able to get to this Full Calendar view - is it possible only EMs see this? 🤔

**Comment by joeyAghion** [comment]
If permissions are limited, maybe one person with the necessary access can generate a feed for all PDDE time off and share it broadly? (And if that works, maybe another scoped to engineering?)

**Comment by admbtlr** [comment]
Yes, that makes sense @joeyAghion , and I'm happy to be that person if necessary. But @jonallured did you hover with your mouse over the _Who's out_ section? For some reason, the _Full Calendar_ link only appears when you hover.

**Comment by jbeyen** [comment]
I can't actually see that view to see all calendars & create a feed - might it only be visible to managers? I am looking on the Home screen.

**Comment by pvinis** [comment]
For the resolution of this, could we also get rid of https://artsy.slack.com/archives/CA3LN4SP7/p1621861205000100 and replace these with the bamboo cal?

**Comment by admbtlr** [comment]
This has been here for a while now because there have been a couple of open questions:

1. Not everyone can see the "Who's Out" calendar in Bamboo
I talked to People Ops and they were unsure whether/why this is the case. I propose that we just take an individual who can see it, have them create a calendar and then share the link. I'm happy to be that individual, unless anyone has a better idea. 

2. It looks like the calendar doesn't get updated properly
I turns out that this happens if you regenerate a link to the calendar - in that situation, the original calendar link stops updating. The solution is to not regenerate the link.

I will bring this up in today's engineering standup, but I think that we should adopt this and move forward with a named individual's calendar.

**Comment by admbtlr** [comment]
Closing this, pending a session with @jasonarias to finesse the details.
