### ISSUE TITLE
RFC: Coordinating Meetings to Free Up Timezone Friendly Calendar Space

### ISSUE THREAD

**Issue by admbtlr** [artsy/README#385]
All times in this RFC are EST, unless otherwise noted. I'm making the assumption that acceptable meeting times are anywhere between 9am and 6:30pm in the relevant timezone.

## Proposal:

We coordinate the times of repeating meetings to ensure that there is as much free calendar space as possible for pairing and cross-team meetings.

## Reasoning

Currently we have team ceremonies, practices and other meetings that all happen at different times. It can be very difficult to find suitable times for ad-hoc and cross-team meetings. With a little centralised coordination, we can standardise our standing meeting times in order to optimise for shared free calendar space. The cross-timezone sweet spot is 9:30am - 12:30pm EST (2:30pm - 5:30pm GMT; 3:30pm - 6:30pm CET). 

## Exceptions:

I'm excluding the Grow team from these proposals because it skews so heavily to the west coast. I think CET - EST collaboration works, as does EST - PST collaboration, but CET - PST is difficult. Currently CX is the only team that spans every timezone, and it only works thanks to the generous willingness of the Californians to start their day absurdly early. This is probably not sustainable in the long run, and I propose that we avoid making such timezone spanning teams in the future.

## Detailed Context and Concrete Proposals:

There are two main areas here: synchronising team ceremonies and reducing general meeting load.

### Synchronise Team Ceremonies
Since we synchronise sprints, it ought to be possible to synchronise the relevant ceremonies. The meetings wouldn't all have to be the same length, but having them start at the same time would increase the amount of free time blocks that are common to all teams.

Current meeting times:

#### Sprint planning
CX: Monday 10 - 11
FX: Mon 12:30 - 1:30
Grow: Fri 2
Platform: Tue 10:30 - 11
Purchase: Friday 10 - 11
PX: Mon 9:30 - 10

#### Sprint retrospective
CX: Friday 11 - 12
FX: Fri 1:30 - 2:30
Grow: Thu 2
Platform: Mon 10:30 - 11
Purchase: Thursday 10 - 11
PX: Mon 10 - 11

#### Standup
CX: Daily 11:50
FX: Mon/Wed/Fri 10:45
Grow: Daily 2
Purchase: Mon/Wed/Fri 10:45
PX: Mon/Tue/Thu/Fri 10:40

#### Backlog Grooming
CX: Fri 10 - 11
FX: Thu 10 - 11
Purchase: Wed 10 - 11 (weekly)
PX: Thu 10 - 11

#### Knowledge Share
CX: Tue/Thu 10 - 11
FX: Tue 11 - 12
Grow: Tue 2
Purchase: Tue 10 - 11
PX: Wed 9:30 - 10:30

#### Conclusions
The 10 - 11 slot is already popular for all the meetings. Maybe we could start by fixing this as a daily team meeting slot. Most teams do planning on either the first Monday or the second Friday, likewise retrospectives. Knowledge Shares usually happen on Tuesdays and/or Thursdays. Grooming usually happens on the last Thursday (although Purchase does weekly grooming). Standups also usually take place within this timeslot.

Based on this data, **I propose that all team meetings happen in the following sprintly slots**:

Monday 10 - 11
Tuesday 10 - 11
Thursday 10 - 11

Tuesday 10 - 11
Thursday 10 - 11
Friday 10 - 11

**I also propose that we synchronise standups at 10:45, on whatever days teams choose to do them**. This means standups overlap with other meetings, but I'm guessing that either meetings can end early, or that teams will be OK with skipping standups if they're already meeting anyway.

#### Practices
We currently have four practices:

**Data** - Tuesday, 9 - 9:45, biweekly

**Mobile** - Wednesday 11 - 12, alternating weekly with office hours

**Platform** - Thursday 11 - 12, weekly (although there is a willingness to go biweekly, which would seem to make sense given the frequency of cancellations)

**Web** - Monday 3 - 4, alternating weekly with office hours. (It would be good to find a time for it that is a little more EU-friendly, especially as the Berlin office grows and the number of likely participants increases. It wouldn't have to be within standard working hours, but an hour or two earlier would be helpful.)

##### Conclusions
It's tempting to align the practice meeting times so that they all happen simultaneously, but that would make it impossible to go to more than one practice. However **I propose that we alternate between practices and office hours in order to make it possible to attend every practice**, e.g.:

Tuesday 11 - 12: Data Practice
Thursday 11 - 12: Mobile Practice, (Platform Office Hour?)
Tuesday 11 - 12: (Data Office Hour?)
Thursday 11 - 12: Platform Practice, Mobile Office Hour

We could leave the web practice out of this cadence for now, but I would appreciate it if we could move to a more EU-friendly slot - maybe 1-2 hours earlier?

### Other Meetings
The remaining repeating meetings on the Engineering Open Meeting calendar are:

#### Engineering Standup
Monday 12 - 12:30

#### Incident Review
Tuesday 12 - 12:30

#### Feedback Friday
Second sprintly Friday 1:30 - 2
I would appreciate it if we could move this to a more EU friendly time, in order to encourage more regular feedback. Perhaps 12 - 12:30?

#### Lunch and Learn
Thursday 6:30 - 7:30
Maybe we could make this biweekly?

## How is this RFC resolved?

We agree on these new times and adjust meetings accordingly. We then enjoy the wide open spaces in our calendars.

**Comment by damassi** [comment]
I'm certainly happy to move the web practice back two hours 👍

**Comment by SamRozen** [comment]
💯 

Thanks @admbtlr for starting this RFC. I definitely agree that it's extremely challenging at this point to schedule ad-hoc meetings with members across different timezone. Aligning key ceremonies across teams and rationalizing practice times would be hugely helpful.

Meeting overload is a recurrent complaint, so I'm supportive of reducing frequency to bi-weekly by default.

In order to implement this, it'll require a coordinated effort. If there's no objection to this RFC, I suggest that we update all the practice meeting invites on Thursday 4/29 and  Friday 4/30 and make it effective starting May 3rd.

**Comment by anandaroop** [comment]
Thanks for thinking this through Adam 🙏🏽. My only feedback is about suggestion to make Lunch & Learn bi-weekly. 

Effectively it already _is_ bi-weekly. The alternating weeks are held for super informal Show & Tell sessions that take place in the same time slot (the calendar invite could be clearer about this — I think it used to be). That also gives us a fallback option on weeks where there is no formal Lunch & Learn scheduled, which is often the case. Given that S&T is a highly optional and informal event, but (I presume) valuable to the cadre of Showers & Tellers who often attend, I'd propose not changing the cadence. But it would be nice to move that to a more CET friendly slot, if that's what you were getting at.

**Comment by sweir27** [comment]
I think I own the Feedback Friday meeting and am very happy to move it up!

Thanks for writing this all out @admbtlr -- I'm very excited to have a more organized calendar 🤩.

**Comment by joeyAghion** [comment]
Paraphrasing: _team_ events are roughly 10-11 ET while _eng.-wide_ events are roughly 11-12? That seems nice and simple.

I second the observation that practice _meetings_ tend to occupy a little more calendar space than they typically need, while practice _channels_ tend to be fairly quiet. It would be welcome to shift that balance a bit, with more asynchronous discussion of timely topics filling any gaps left by biweekly meeting schedules.

**Comment by damassi** [comment]
> Paraphrasing: team events are roughly 10-11 ET while eng.-wide events are roughly 11-12? That seems nice and simple

There's been the caveat for Grow, but its worth mentioning again that these times are early for the west coast US.

**Comment by pvinis** [comment]
Fun idea, good investigation, and I think it would help teams and people sync better! We should definitely link or move this to the notion page for team workings that Sarah and Adam-I made. I don't think this is a requirement for any team, but it would definitely help a lot if they do stick to it or at least start there and adjust as needed.

**Comment by erikdstock** [comment]
Thanks for thinking all of this out- I've been a part of exercises like this for just my team in the past and it was incredibly difficult to keep all these strands in my head. One note for purchase team is that some people have been splitting time in the west coast recently so we also have some 10am EDT meetings that span west coast > berlin. However this RFC wouldn't make that any worse. I am 👍 .

**Comment by admbtlr** [comment]
## Resolution
Let's do it

## Level of Support
2: Positive feedback.

## Next Steps
PMs, Team Leads and Practice Leads should move all repeating meetings into the following timeslots (all times EST, days are listed sprintly):

#### Team Meetings
 Monday 10 - 11
Tuesday 10 - 11
Thursday 10 - 11

Tuesday 10 - 11
Thursday 10 - 11
Friday 10 - 11

#### Standups
10:45, day to day cadence is up to individual teams

#### Practice Meetings
Tuesday 11 - 12: Data Practice
Thursday 11 - 12: Mobile Practice, (Platform Office Hour?)
Tuesday 11 - 12: (Data Office Hour?)
Thursday 11 - 12: Platform Practice, Mobile Office Hour

#### Exceptions
The Grow team, since they skew west coast US.

**Comment by damassi** [comment]
Noticing that the Web Practice is missing from the list -- deliberate?

**Comment by admbtlr** [comment]
Thanks @damassi. Since it's pretty much impossible to find a good time for the web practice that works in all timezones, I don't think it makes sense to prescribe a time here, but as I said in the RFC,

> We could leave the web practice out of this cadence for now, but I would appreciate it if we could move to a more EU-friendly slot - maybe 1-2 hours earlier?

How about moving it to 1pm - 2pm on Tuesdays? That would keep the Tuesday/Thursday rule for practices, and make it more do-able for people in the EU.

**Comment by damassi** [comment]
We can totally make 1pm EST Tuesday work 👍
