### ISSUE TITLE
RFC:🚰 Water Cooler Break

### ISSUE THREAD

**Issue by chr-tatu** [artsy/README#398]
## Proposal: **🚰 PDDE Water Cooler Break**
A **_water cooler chat_** describes a casual conversation between co-workers about non-work-related topics.

### Proposal details
🗓️ **Fortnightly 30min Zoom meeting** at a time slot that suits multiple time zones, for instance: 
- Mondays, 17:30 CEST / 11:30 am EDT (before the Engineering Stand-up)

👻 **Rotating host**
- The host greets the group and announces the ice breaker (examples: [here](https://blog.sli.do/virtual-icebreakers/), [here](https://www.tinypulse.com/blog/44-virtual-icebreakers-and-team-building-activities), [here](https://cliquestudios.com/wp-content/uploads/2020/12/Water-Cooler-Topics.pdf?x56671)). It's up to the host to decide on the topic.
- They split the participants into Zoom Breakout Rooms of 3 or 4 people.
- At the end of the meeting they will ask for a volunteer to host the next Water Cooler Break.

💬 Channel (#pdde-watercooler)
- Where everyone can share pictures, links, ideas, and thoughts about their conversation or the icebreaker topic.

## Reasoning
Artsy is a growing distributed-first company. We would like to break the virtual boundaries and bring together people who are not working closely on a daily basis. It's an opportunity to get to know your colleagues - old and new - and to have a fun break.

## Additional Context
We have tried different experiments in the past that didn't prove successful. We learned that successful gatherings have a host driving them. Currently, similar events happen either location-based or team-based. We want to break those boundaries, but we learned that having the entire Artsy joining these events felt overwhelming. This time we would like to try a PDDE only event.

## Exceptions
Aiming for a time slot that suits multiple time zones is hard to achieve. The proposed time slot might be a stretch for people on the US West Coast or in Asia. Feel free to propose improvements. Any feedback is great!

## How is this RFC resolved?
For a week, we will collect feedback and check the engagement for having such an event. We will try to incorporate your comments and feedback in our first **🚰 PDDE Water Cooler Break** event.
This experiment will be running for one month. With enough engagement, we will continue having the breaks. Otherwise, we look for other ideas.

**Comment by pvinis** [comment]
I like this :). many teams have a coffee but a company-wide one would be cool.

one quick comment, choose the host somewhere before the end, so it's not forgotten 😅, but it could be done on slack async.

**Comment by kajatiger** [comment]
We do also have a global coffee meetup, but one time I went, we were only around 6 people and it was really nice and didn't need a break out room. I am open to trying out the water cooler thing!

**Comment by chr-tatu** [comment]
@kajatiger : Are you referring to the one on Thursday morning CEST? We were also 6 people when I joined. It was a nice coffee meeting.
The difference I see is that the one on Thursday is focused on Europe + Asia. This one is focused on PDDE and Europe + US.

**Comment by chr-tatu** [comment]
> We do also have a global coffee meetup, but one time I went, we were only around 6 people and it was really nice and didn't need a break out room. I am open to trying out the water cooler thing!

@kajatiger : Are you referring to the one on Thursday morning CEST? We were also 6 people when I joined. It was a nice coffee meeting.
The difference I see is that the one on Thursday is focused on Europe + Asia. This one is focused on PDDE and Europe + US.

**Comment by erikdstock** [comment]
I'm fine with this but would rather use or repurpose an existing channel (#dev-banter, #dev-offtopic)... just a personal preference, but I don't personally find any of our slack channels to be too chatty or busy to absorb some friendly conversation (except channels that have been taken over by bots). Non-blocking.

**Comment by chr-tatu** [comment]
> I'm fine with this but would rather use or repurpose an existing channel (#dev-banter, #dev-offtopic)... just a personal preference, but I don't personally find any of our slack channels to be too chatty or busy to absorb some friendly conversation (except channels that have been taken over by bots). Non-blocking.

That's a very good point. We also have #tech-culture. The concern I have is that the break is for PDDE, including design and PMs. Is there any existing offtopic channel for all PDDE that we could use?

**Comment by erikdstock** [comment]
> Is there any existing offtopic channel for all PDDE that we could use?
how about a #pdde-offtopic channel? General but good compromise for me.
