### ISSUE TITLE
[RFC] Feedback Friday time reschedule

### ISSUE THREAD

**Issue by gkartalis** [artsy/README#403]
## Proposal:

I would suggest to reschedule `[At Desks] Feedback Friday` event to a more EU friendly time (as it currently is 19:30 - 20:00 CEST aka Berlin time) 

## Reasoning

The current time of the event (as it currently is 19:30 - 20:00 CEST aka Berlin time) is outside of most EU people working hours (i.e. me) thus we might forget to actually schedule some heads down time on it.

## Exceptions:
✨ None ✨
## Additional Context:

[Original Feedback Friday RFC](https://github.com/artsy/README/issues/248)

## How is this RFC resolved?

If we could agree on changing the time of the event to be in a more time-zone neutral time.

**Comment by mdole** [comment]
good call @gkartalis !! I used to be the person who would nudge people during "feedback friday" time, and since moving to Berlin, I've completely forgotten to do it since the old time was so late. Thanks for resurfacing!

**Comment by pvinis** [comment]
Matt's nudge was one awesome thing, and I have had a personal slack reminder for this, on a time that is easier for me. I think we could totally make a slack reminder for this or reschedule the cal event or something else.

That's a very long way to say, I agree with this RFC :D
