### ISSUE TITLE
RFC: Catch more WTFs during onboarding

### ISSUE THREAD

**Issue by jonallured** [artsy/README#407]
## Proposal:

Update our onboarding checklist to specifically call out that we want to hear the WTFs from new hires. Also encourage the hiring manager to discuss these items during the first few weeks and beyond.

## Reasoning

People new to Artsy are in the best position to look at our behaviors and practices with fresh eyes and call out the places where we have inadvertently [normalized deviance][norm-dev]. Something as simple as a package name all the way to using a document database rather than a relational one - it's valuable to be reminded of and consider changing these things. We can't do this important work if we aren't capturing the elements of our systems that surprise people!

[norm-dev]: http://danluu.com/wat/

## Exceptions:

None.

## Additional Context:

This RFC was inspired by this Slack thread:

https://artsy.slack.com/archives/C03J4L2KK/p1631113490015300

Which links to this video:

https://www.youtube.com/watch?v=8bxZuzDKoI0

More here:

https://blog.danielna.com/talks/pushing-through-friction/

And here's the current checklist:

https://github.com/artsy/potential/blob/main/.github/ISSUE_TEMPLATE/engineering-onboarding.md

## How is this RFC resolved?

A PR to potential that calls out our desire to hear about the WTFs new hires feel and a nudge for them to write them down as they are having them. Then something (?) to nudge the hiring manager to discuss these items with the new hire and surface them more broadly.

**Comment by jacobherrington** [comment]
I just finished watching that talk; I really enjoyed it! I totally agree with the suggestion to incorporate it into the onboarding material.

Being a new hire, I can see how codifying this practice would be extremely encouraging. Even as a fairly outspoken person, I'd probably do a better job of collecting and sharing my thoughts if I saw it as explicitly "part of my job" while onboarding.

Does it make sense for us to document/automate a process specifically for capturing and sharing feedback from new employees? We could use a Slack bot or Lattice? Finding a place where newer employees can keep track of their "WTFs" as they occur and render that feedback via a semi-private channel seems ideal:
>A PR to potential that calls out our desire to hear about the WTFs new hires feel and a nudge for them to write them down as they are having them. Then something (?) to nudge the hiring manager to discuss these items with the new hire and surface them more broadly.

**Comment by jonallured** [comment]
Seems like people are into this idea so I opened https://github.com/artsy/potential/pull/423 to get the ball rolling. If we feel like we need more structure - a Slack bot, Lattice template or whatever we can do that but I wanted to get something going and learn how it performs before putting more effort into this.
