### ISSUE TITLE
Remove single line breaks in Markdown files

### ISSUE THREAD

**Issue by dblock** [artsy/README#42]
## Proposal:

Remove any single line breaks in Markdown files. 

## Reasoning

It seems like many have an 80ish character line break, which seems completely unnecessary as all editors do just fine with wrapping text.

## Additional Context:

The extra CR/LFs are driving me bananas.

This could be automated via Danger.

**Comment by orta** [comment]
Prettier creates the [line breaks](https://prettier.io/blog/2017/11/07/1.8.0.html) automatically, I'm against removing them TBH, it feels much nicer to have consistently organized docs.

**Comment by jonallured** [comment]
FWIW, my Vim setup also automatically wraps MD at 80 and I'm very used to it and like it. 🤷‍♂️

**Comment by damassi** [comment]
Pretttier takes care of things, and during editing VSCode (if that's your editor) hooks into prettier and automatically handles formatting on save. If VSCode isn't your editor, there def setup steps one could follow to get things working as one would expect.

**Comment by dblock** [comment]
Since there are no strong opinions on doing this the _right way_™, I'll close this.

**Comment by jjyotikataria** [comment]
@orta @jonallured @damassi 
@alloy 

Can anyone please help me with removing extra whitespaces/line breaks before and after the plot in markdown?

**Comment by tormyvancool** [comment]
Honestly it will be nice. Especially to avoid line breaks when HTML code is used into.
