### ISSUE TITLE
RFC: Adopt Codecov at Artsy, starting with Gravity

### ISSUE THREAD

**Issue by lidimayra** [artsy/README#422]
## Proposal:

Adopt Codecov at Artsy, starting with Gravity

- Configure codecov to comment in the PRs with coverage results and link to codecov results page
- If a PR is opened that decreases the test coverage, should we block it?
  - No, enforcing a hard block would probably lead to more frustration without incentivizing us to improve our tests
- Why start with Gravity?
  - Code coverage tools seem to be most useful for backends
  - We could consider adopting for our frontends, but it seems like it might be harder to adopt consistently and with good results

## Reasoning:

- Helps us to see when our code is poorly structured: if you feel that covering all of a class is difficult, it might mean that the class needs to be refactored!
- Enables us to refactor with more confidence by knowing which parts of code are not covered. Even though Codecov won't force us to have high-quality tests (this is something to be enforced by ourselves when writing and reviewing code), it will give us visibility on what's tested and what's not. 
- Allows new engineers to better understand the code by reading tests as documentation
- Makes major dependency updates easier to be tested
- Helps us see where there are gaps in our test coverage - even if we choose not to add tests where we're missing them, we can make sure to manually test those portions of a code change

## Exceptions:
None

## Additional Context:

https://about.codecov.io/

## How is this RFC resolved?
Deciding whether we want to adopt codecov or not and in case we do start this setting with Gravity as an experiment.

**Comment by kajatiger** [comment]
I definitely like that it will spare the reviewer the hint that there is a test missing for a new implementation. I like when tools are taking over these kind of simple jobs. In the past I have had different experiences... Sometimes it was useful, and sometimes the tool kept being ignored and in the end was just hindering work. I think it also depends on the configuration and usage. But I am definitely up for a try.

**Comment by anandaroop** [comment]
I'm intrigued. We've done this very sporadically for some projects ([example](https://coveralls.io/github/artsy/estella?branch=master)), but I can't recall conversations about pros & cons myself.

One suggestion is that if we do proceed with this, we might trial it on a smaller Rails project than Gravity to begin with, to get a better idea if we should adopt more widely.

Actually now that I'm poking around I see that Exchange [used to have this enabled](https://coveralls.io/github/artsy/exchange) but it seems like it was turned off at some point? It might be fruitful to ask that team why.

**Comment by lidimayra** [comment]
Hmm, that's a very good point!! As I understand, Exchange is mostly maintained by @artsy/transact-devs and @artsy/px-devs, right? Would you have some thoughts to be shared on this?

**Comment by lidimayra** [comment]
Great inputs, thanks a lot, @joeyAghion !!

Based on these points, I would think if it would make sense to discuss setting up just simplecov as a code coverage analysis tool (without necessarily integrating it with codecov). What would you think?

**Comment by joeyAghion** [comment]
I'm not that familiar with simplecov or how that would make the integration simpler. Assuming that's the case, though, I'd be open to it. I second @anandaroop's suggestion to pilot with a smaller Rails project first (like maybe by fixing/replacing Exchange's tooling).

**Comment by lidimayra** [comment]
In that case, would it make sense to think about this as a Future Friday project?

**Comment by lidimayra** [comment]
## Resolution
We decided codecov might not be the ideal option, but we would like to have coverage data somehow. We'll work on an initial setup for Exchange as a Future Friday project

## Level of Support
5: Unclear Resolution.

## Additional Context:
Depending on the results of the FF implementation, we'll have more clarity on what would be the best approach for us

## Next Steps
[Future Friday project](https://www.notion.so/artsy/Future-Friday-projects-outcomes-20e796fae93b48f38a79ec0af6de028b?p=6c46c1983be240228e0402db1471840d)
