### ISSUE TITLE
RFC: Rename product slack channels to `prd-*`

### ISSUE THREAD

**Issue by pvinis** [artsy/README#436]
## Proposal:

~~Rename all slack channels from `product-*` to `prd-*`.~~
Rename all slack channels from `product-X` to `X` or `X-team`.

For example: `product-mobile-platform` -> `mobile-platform` or `mobile-platform-team`.

## Reasoning

- Now that we have a lot of product teams, many with long names, its hard to see the names on slack.
![Screenshot 2022-01-21 at 14 30 06](https://user-images.githubusercontent.com/100233/150527411-80bb7776-0f82-4299-83b4-587258aee5d0.png)
- ~~It would align with the developer channels called `dev-*`.~~
- There is a much better way to "namespace" these channels like [here](https://github.com/artsy/README/issues/436#issuecomment-1019583283) and [here](https://github.com/artsy/README/issues/436#issuecomment-1019728910)

## Exceptions

Probably `product` and `product-updates` can stay as they are.

## Additional Context:

N/A.

## How is this RFC resolved?

I will contact the owners of the channels and/or J to rename these. They are just a few, it shouldn't take long to rename them all one by one.

**Comment by damassi** [comment]
Note that the sidebar is draggable:
![expand](https://user-images.githubusercontent.com/236943/150625962-45fde474-e96b-4314-9602-4928b6e37687.gif)

**Comment by pvinis** [comment]
it is, I know, but it's basically useless area. I much prefer more space for the chat then the channel names.

**Comment by damassi** [comment]
In any case, going from `product` to `prd` -- a different of 5 characters -- doesn't actually fix the problem, as most product channels are many characters. On my 15' MBP, the sidebar (where all of the channel names are clearly visible) is 300 pixels wide, and the chat area is 1300 pixels wide. How much wider does chat need to be? For someone not working from a laptop, the chat area is even wider.

**Comment by pvinis** [comment]
threads split the chat area, and I usually keep both. but yea, there is always enough space, but also there is the easy rename. namespacing channels feels purely like a thing that could be a slack channel category or something 🤷‍♂️

**Comment by dblandin** [comment]
One can widen the sidebar to give more space for channel names if desired and it's pretty easy to hide the sidebar completely when you want to focus on chats/threads via the icon or Cmd+Shift+D shortcut.

I personally like to keep the sidebar closed and use Cmd + K to switch channels.

While the org could likely adapt to a new `prd-` prefix, it doesn't feel as intuitive as a `dev-` prefix is to developers. This change would also break some links and references in external resources like Notion.

**Comment by joeyAghion** [comment]
I'm not a fan of the `product-` namespacing, but I'd rather not introduce another abbreviation either.

These namespaces predate Slack's ability to group channels into "sections." Now that we can each choose the groupings that make sense to us, I think we could eliminate the namespaces altogether. (Instead most of these could just be named `*-team`, which is self-explanatory.)

<img width="219" alt="Screen Shot 2022-01-23 at 5 43 48 PM" src="https://user-images.githubusercontent.com/28120/150701014-33e46f7c-b0e8-4147-8aa4-2fa69470a25f.png">

**Comment by pvinis** [comment]
totally up for that too. thanks for the suggestion!

**Comment by damassi** [comment]
@joeyAghion - what is this slack channel grouping feature and why does everyone not know about it!?

**Comment by kathytafel** [comment]
Can we close this then @pvinis, given the magic we just learned?

**Comment by pvinis** [comment]
I would say instead of closing, we repurpose this to change `product-X` channels to `X` or `X-team`.

**Comment by kathytafel** [comment]
are all the product leads on GitHub? Is this the right place to poll for their opinion?

**Comment by erikdstock** [comment]
Just want to comment that slack has a concept of channel prefixes: https://slack.com/help/articles/360033618294-Create-channel-prefixes-for-your-workspace

**Comment by damassi** [comment]
The thing with renaming, is folks don't know about groups. We shouldn't make other's slack environments more chaotic, or force folders on folks. This seems to be individual preference.

**Comment by erikdstock** [comment]
In my volunteer slack which does not have folders (Free tier) we have introduced single-letter prefixes so they naturally appear grouped at the top of a list.

**Comment by kajatiger** [comment]
I agree with @joeyAghion and would not introduce another abbreviation, but on the other hand like a prefix for grouping. Another inconistency I want to point out is that we are almost always using team abbreviations when we speak. When I use PX and NX all day and then have to translate this in my head to "product-partner-experience" and "product-negotiate" I have to make an extra brain effort that I would like to avoid when quickly looking up team channels.
And also @damassi I share your feelings about learning that there is a grouping feature. This RFC has already improved my life.

**Comment by SamRozen** [comment]
+1 to @kathytafel comment on consulting with the non engineering folks of PDDE so Notion might be better suited to circulate this info.

I'm understand the drawback of long prefix. What the prefix helps with though is discoverability. When someone new joins PDDE they know they should join most if not all product- channel. Beyond new joiners, data or design folks who straddle multiple teams also benefit from this consistency and discoverability. 

I'm not against dropping the prefix but then we need to find a way to make it easy for everyone to know all the relevant PDDE channels. (That's also important for folks outside of PDDE.) 

Last, the slack channels also match the email distribution list. Again this consistency has made it easier to know who to ping etc for external stakedholder or new joiners to find what group to be added to get the right calendar events, etc.. What's your proposal to address that?

**Comment by pvinis** [comment]
I think for new joiners it totally makes sense. I have used `dev-` as a search term to see these channels.

## Resolution
**Not** renaming.


## Level of Support
6: RFC Rejected.

#### Additional Context:
The grouping seems really helpful for some of us, and the namespacing is still helpful to newcomers. Seems like everyone in this RFC, agreeing or not, is at a better place than before.

## Next Steps
Have a nice rest of your day.
