### ISSUE TITLE
RFC: Host one Codebase Refinement per quarter in 2022 

### ISSUE THREAD

**Issue by patrinoua** [artsy/README#458]
## Proposal

Treat code as a product: One that needs to grow by planning and refinement. 

In the same way we collect feedback for product and our people at artsy, we could collect feedback for our code. 

We provide feedback to our people every quarter and this helps everyone develop. A similar approach to our code base could further improve the code base and dev experience.

Instead of doing that on a product team level we can address it by which repositories people work on: Those who work mainly on eigen can suggest improvements to eigen, those who work on force can suggest improvements for force and so on.

Once per quarter, and in the same way we do Hackathon, we could dedicate 3 to 4 days for our codebase refinement.

## Reasoning

- This is a big project that has been going on for more than 10 years. A lot of people have worked on it, different conventions have become popular and everyone has their specific coding style. 
So it would be useful to examine a common coding style on a company level.

Plus a lot of the reasoning in Matt's RFC about [Hackathon](https://github.com/artsy/README/issues/441) applies:
- Excitement: good for morale! People enjoy working on a nicely organised code base, help out their coworkers, and learn new things
- Impact: high-impact things happen when we get to dream up projects. Good for the business too!
Innovation: they help us trial new technologies!
- Camaraderie: Artsy is mostly remote these days, which has made it hard to build connections across the organization. Refinement give us a forum to connect with people within PDDE and doing them every quarter would mean we have more of these opportunities for connection
- Prioritization: Refinement help inform product team priorities and work. 
- Return on investment: low-lift, high-impact improvements to admin tools and team workflows. While we’re working on addressing these issues within regular PDDE teams, sometimes things slip through the cracks or just don’t get surfaced at the right time! A Refinement process can help keep Artsy running like a well-oiled machine.

## Formatting

We could have 

1. A brainstorming meeting 
1. A planning meeting where we select some of the ideas that came up on the brainstorming
1. Jira boards for each repo where we add everything that has been decided upon
1. A few days to execute

<img width="778" alt="Screenshot 2022-03-29 at 14 10 31" src="https://user-images.githubusercontent.com/36475005/160608251-a1408341-a037-49b0-861c-2fe4dd4e6d64.png">

#### 8 April 2022 Update 
After the positive feedback we've started collecting some of the ideas [here](https://www.notion.so/artsy/Refine-a-thon-30ab8c33ad654c8aa84e67d499d7e6ea). Feel free to contribute! :)

---- 

## Resolution
After the positive feedback we decided to do this. 

We have started collecting some the ideas [here](https://www.notion.so/artsy/Refine-a-thon-30ab8c33ad654c8aa84e67d499d7e6ea), feel free to contribute! 

While this RFC proposes one refinement per quarter we haven't finalized the cadence of it.
 
## Level of Support
1. Overwhelming positive feedback.

## Next Steps
We will use the next Hackathon slot (end of June) as a first iteration and by the end of the first refinathon we will discuss outcomes, and decide on the cadence. @patrinoua will be the DRI for these discussions.

**Comment by kajatiger** [comment]
There are not enough ❤️ emojis that I can give to this RFC. I am so into this!!!!

**Comment by damassi** [comment]
In the absence of a FE platform and Internal Tools team, I think this is the missing piece i've been looking for 👍 I also suspect people very much like working on this kind of thing (regardless of skill level) so also agree that it'd be great for morale.

**Comment by sweir27** [comment]
This sounds exciting/intriguing! When we were discussing the quarterly hackathon idea, someone raised that we could use the time for other things besides hackathon. So if it achieves similar goals and we're excited about this, perhaps we could use the next hackathon slot to try it out?? (cc @mdole as the DRI 😄)

**Comment by patrinoua** [comment]
> My one question is: What about Future Friday? Since that occupies a lot of this sort of space. However, I don't think FF is good at generating momentum in the same way that an organized event is, and in general only a few people publicly participate.

Future Friday is great for addressing smaller issues that can be decided by upvoting in some of the dev channels. But with one day every 2 weeks it's not really possible to address what this RFC suggests.

**Comment by kajatiger** [comment]
>  it could be "Gravity: Migrate the Artwork model to Postgres (😅)"
Only this ☝️  would already be enough reason for why we need the refine-a-thon and I think almost everyone in engineering thinks that this is urgent and needs to be addressed. 
Thanks @mdole for making the RFC more haptic by giving such a great example for what we could do.

I think similar to the hackathon, we should collect ideas beforehand for the refine-a-thon and then form little temporary teams for the projects. We could also create a manifest of code-values before in order to align the goals/outcome of each refine-a-thon... The manifest would define what things like consistency, security, accessibility, good design, expandability etc. mean to us with examples in where it is done well vs. where it still needs to improve.

**Comment by patrinoua** [comment]
@mdole I love the name of "Refine-a-thon", thanks! 😄

And I 100% agree that some preliminary work is necessary.

This is why I added a planning session, but something before that would also be nice to have:

We could have a couple of things:

A notion page for each repo where people add things. [example](https://www.notion.so/artsy/2673214ebb1f4693bf7b93f7d88cecee?v=a7c96c2dbf84404aad0c1bdaaa2e4902) 
We could also send out an email once per month with a google form questionaire where ask people 
which repo or repos they work on and to provide feedback, what they liked, what could be better, things they'd like to add etc, which we could later use to further populate our repo-notion pages.

**Comment by fladson** [comment]
Love this idea, thanks for raising it. I will try to add some tech debts to the notion board.

**Comment by patrinoua** [comment]
After the positive feedback we've started collecting some of the ideas [here](https://www.notion.so/artsy/Refine-a-thon-30ab8c33ad654c8aa84e67d499d7e6ea)

**Comment by patrinoua** [comment]
## Resolution
After the positive feedback we decided to do this. 

We have started collecting some the ideas [here](https://www.notion.so/artsy/Refine-a-thon-30ab8c33ad654c8aa84e67d499d7e6ea), feel free to contribute! 

While this RFC proposes one refinement per quarter we haven't finalized the cadence of it.
 
## Level of Support
1. Overwhelming positive feedback.

## Next Steps
We will use the next Hackathon slot (end of June) as a first iteration and by the end of the first refinathon we will discuss outcomes, and decide on the cadence. @patrinoua will be the DRI for these discussions.
