### ISSUE TITLE
RFC: Reusable components

### ISSUE THREAD

**Issue by patrinoua** [artsy/README#465]
## Proposal

_mobile dev specific rfc_
- Create components in a reusable way.

- Small and medium size components (atoms, molecules, organisms) are developed in a dedicated folder (palette) where they can be easily discovered, and reused by other engineers. Moreover it will be easy to transfer them between different projects (eg. eigen, energy)

- Use the same structure as in [Design](https://www.figma.com/file/gZNkyqLT8AU3T61tluVJyB/%F0%9F%A5%B7%F0%9F%8F%BBArtsy-3.1-Design-System?node-id=604%3A1770) (atoms, molecules, organisms)
<img width="875" alt="Screenshot 2022-05-18 at 5 57 46 PM" src="https://user-images.githubusercontent.com/36475005/169088181-ef19de6e-d42d-4e21-acef-4b30356bccf1.png">

- Components are always created on a common place instead of locally in the files where they will be used

## Reasoning

<img width="593" alt="Screenshot 2022-05-18 at 5 39 03 PM" src="https://user-images.githubusercontent.com/36475005/169087310-4b643bfe-4847-406d-8a80-b94878831ca2.png">

### Modularity
**Simple things make firm foundations**
https://www.w3.org/DesignIssues/Modularity.html

- One module can evolve or be replaced without affecting the others. 
If the interfaces are clean, and there are no side effects, then a developer can redesign a module without having to deeply understand the neighboring modules.
- easy to update
- easy to debug
- easy to test
- easy to demonstrate using storybook
- everyone knows where components are and they don't have to redevelop

### React components are made to be reusable

> Components allow you to split the UI into independent, reusable pieces, and think about each piece in isolation.

According to the react docs https://reactjs.org/docs/components-and-props.html

### What are the advantages of reusing components?

- Code that is less prone to bugs (we only need to debug in one place instead of 3 for example)
- Speed (we only need to create things once) and with a quick look on storybook we can know if something has already been created (and tested) or not.

## Additional Context

Atomic Design is a way to organise our components library with a hierarchy depending on size (atoms are one piece, molecules are a combination of atoms and organisms are a combination of molecules). 

Read more about atomic design here [https://atomicdesign.bradfrost.com/chapter-2/](https://atomicdesign.bradfrost.com/chapter-2/)
## How is this RFC resolved?

A PR to peril-settings adding the check

**Comment by patrinoua** [comment]
In eigen and now energy it often comes up that we develop components locally, this is what this RFC is addressing. [Here](https://github.com/artsy/energy/pull/17#discussion_r875772869) is an example.

**Comment by patrinoua** [comment]
Thanks, I've added that in the description :)

**Comment by MounirDhahri** [comment]
@dzucconi to your point, we do use `palette` as well in mobile and as far as I know, we have as well the atoms created by design extracted inside it.

**Comment by MounirDhahri** [comment]
@patrinoua IMO, I believe we should still stick to the same logic described [here](https://github.com/artsy/palette#does-my-component-belong-in-palette) and that we've been using so far

> ### Does my component belong in Palette?
> If the component applies to Artsy as a brand and can/will be used across multiple digital products, then Palette is a great place for it. If it's highly product specific then it's best to leave the component where it's used. We can always move things later!

The reason behind that is that we still want to keep using `palette` (or `palette-mobile`) for both `eigen` and `energy`.  Both repos could still have their own shared components, and that's totally fine IMO, but I don't think those components should move to `palette` unless they get added to our design system by design. The example you cited above (this [one](https://github.com/artsy/energy/pull/17#discussion_r875772869)), is a good example of a component that's only specific to `energy` that I don't think we should be moving to `palette`

**Comment by patrinoua** [comment]
@MounirDhahri thanks for elaborating. 

My suggestion is to have components developed in a central place of information. 

Advantages being that 
1) It does not take extra time
2) the file can be in one central location with its test and storybook file (clean and modular code)
3) If/when we need to use it again we can quickly find it

The equivalent in a kitchen would be keeping the spices with spices, pasta with pasta and cutlery with cutlery instead of having everything in one shelf. 👩🏻‍🍳

We have a figma file with the design system (currently V3.1) and we can assume that we use the same design system through out the app/apps, but if the different apps have different design systems we can easily create a palette for each design system. 
That could be palette-mobile, palette-eigen or palette-energy or whatever the scope of it. However, since I don't think there would be so many differences between the components I do not see a need for that diversification. 

Even if a component is only going to be used once by one app, it's still good to have it on a central place instead of inside the place where it will be used. Because if it is used once, who knows, maybe we'll need it again, and then it will be ready for us.

Otherwise we are assuming that when they want to create something that already exists developers know the app so well and know where they can find things that are locally defined. 
Then because of spaghetti code there is the risk of having to un-spaghetti the code before reusing it, and then go ahead and copy paste code locally. 

This increases friction when we want to update or debug a component, because maybe the component is updated in one place but not everywhere.

It often happens that people develop a component that already exists from scratch because they didn't know the component is already developed somewhere and it's easier to just make it from scratch than search around a huge code base.

The opposite of what I am suggesting is defining things locally in the file where they are used, which is often the case now. 
I do not see the advantage of doing things this way, however if there are some I'm interested in finding out more about that.

**Comment by damassi** [comment]
@patrinoua - can we concretely show show how it currently is, and how you would like it to be, maybe with a mock file tree and some code examples in the description? I'm having a little trouble understanding. Is the RFC a request to update organization of existing palette components around atomic design? 

I see [this comment here](https://github.com/artsy/energy/pull/17#pullrequestreview-976780658), and we should certainly be more diligent about creating reusable components. If indeed the `ArtistThumbnail` here is generic enough to be reused globally, why not move it to a centralized location? Often times theres a balance tho -- there's something that _should_ be generic, but in practice its not worth it and a one-off component is fine.

**Comment by araujobarret** [comment]
I'm also a bit confused 😅 ; we already do that in [Force](https://force-storybook.artsy.net/) and [Palette](https://palette-storybook.artsy.net/) and we thrive for this type of modularity, sometimes re-visiting components to remove some extra batteries and/or add.

In regards to the way we design the components @damassi made it simple, IMO this RFC needs some examples of good/bad examples.

**Comment by patrinoua** [comment]
I am sorry if this is confusing, I will try to elaborate more on my suggestion.

Jonathan and the rest of the designers took the time to organize the different components we use in atomic design principles.

I suggest using the same principles to organize our components with code.

This way we won't have to debate on each component "Should I add this to palette, should I not add it to palette"
Adding things to palette is free ✅ and it makes them easier to find ✅. 

So I am wondering why we would not add things there (in our toolkit) and define them locally instead.

I am suggesting an **a priori** rather than an **a posteriori** approach, where we expect that components might be reused and have them ready, rather than define them once locally and the second time we want to use them either define them from scratch (the quick solution) or search for them, modularize them and add them to palette.

**Comment by patrinoua** [comment]
Here is also an example: 

We have at least 3 places on eigen where we have upload photo functionality.

Because we do not have a modular component for doing that job, last time we had to do that we had to create the functionality from scratch, with copy paste code. [Here is the PR](https://github.com/artsy/eigen/pull/6176/files#diff-a26cca2d74d348616e484cfa939a3a9e1f0fdce71dd784640fc2895e6a18480f).

Photo upload is a process much more husty and we dedicated at least a week last time we developed it, with using all the functions with all the repos, testing etc. 

If we had a generic component we could easily just use that one and not have to dedicate all that time on making it from scratch which is basically copy paste and change a few things. And the next person will have to do the same: The whole process again, copy paste and change a few things.

Imagine if we have to refactor this because some of the APIs works differently now, we'd have to do it in 4 places instead of just one.

**Comment by pvinis** [comment]
> not have a modular component for doing that job, last time we had to do that we had to create the functionality from scratch, with copy paste code. [Here is the PR](https://github.com/artsy/eigen/pull/6176/files#diff-a26cca2d74d348616e484cfa939a3a9e1f0fdce71dd784640fc2895e6a18480f).

One could argue that this could be the point where this component becomes shared. Maybe not on the first use, maybe not the second, but maybe the third we move it over. 🤔

**Comment by patrinoua** [comment]
Well maybe we dont need to use it again, who knows?
What is the advantage of doing it on the third time after I dedicated 1 week every time instead of just doing it from the first time?
I'd like to understand the blocker.
We don't want to overcrowd our palette with elements we may just use once? Why? Is it bad for performance, too much info or what is the argument against doing that?

**Comment by pvinis** [comment]
> Well maybe we dont need to use it again, who knows?

that goes against what you are suggesting? You said we should go to palette-mobile by default, but here, if we don't use it again, we shouldn't?

> what is the argument against doing that?

others might feel differently, but for me personally, I guess I try to judge if something is going to be reused or not. Not always a correct guess. But I feel that first guess becomes more concrete after something I thought would not be reused, ends up actually being reused. and I prefer to start local, only because (to me) if feels easier to "promote" something from local to palette-mobile, than it is to "demote" from palette-mobile to local. I'm not saying that way is correct, or the best way. I'm just saying that's usually on my mind when I need to decide where to put a component.

But I agree that many times we don't go to palette-mobile even when we should. Sometimes it slips my mind. Sometimes I'm biased by the workflow that I don't want to do the 1, make change on palette, 2, make a pr, 3, wait for canary, 4, try it on force. That's why I want us to do better for palette-mobile. And maybe an easier/faster workflow would make me and others be more easily convinced to put things in palette-mobile directly 🤔

**Comment by patrinoua** [comment]
Just playing devils advocate! 😈 

I also think that once you've already used the component a few times (3 in this case) maybe you don't need it a 4th time. 

But maybe you do! 

If we had made a component reusable in the first place we would have skipped the extra time of developing it for the second and third time and refactoring it 3 times, if we now decide to make it reusable.

I do not believe in a class system where some components deserve to be in palette and some not. All components are equal and deserve to be palettised and reusable! 
Tested. Posing on Storybook. 💃

And yes this should be part our normal development circle and not an extra thing to do that needs too much work, otherwise it would never work :)

**Comment by patrinoua** [comment]
Thanks @dzucconi.

I agree that the package size could be bigger. 
This is why we could have different palette scopes (eg palette-eigen, palette-energy). 
We could then easily copy things from one or the other whenever we need to use something.

This would be more performant in comparison with redefining the same component again and again, and easier to maintain, update, and debug.

To your second point about flat hierarchy, I am not suggesting a flat hierarchy, but rather adopting the same hierarchy we use on our [design](https://www.figma.com/file/gZNkyqLT8AU3T61tluVJyB/%F0%9F%A5%B7%F0%9F%8F%BBArtsy-3.1-Design-System?node-id=604%3A1770) which is following the atomic design principles. 
You can find out more about it here: https://www.notion.so/Atomic-Design-2ab2d50063934e87b5f989c0a8c31b64

I hope that makes sense 🙏

**Comment by patrinoua** [comment]
Thank you everyone for your contributions. 🙏
After collecting feedback both from here and from 1-1 conversations, I'll now close this RFC and soon make another one, where it is more clear what we are hoping to achieve and in which way this could be done.
