### ISSUE TITLE
RFC: Completely Remove Team Lead Updates

### ISSUE THREAD

**Issue by jonallured** [artsy/README#56]
## Proposal:

Drop the [Team Updates agenda item](https://github.com/artsy/README/blob/master/events/open-standup.md#what-is-a-good-update) in Engineering Open Standup.

## Reasoning

I successfully got [Reduce Duplication at Engineering Open Standup](https://github.com/artsy/potential/issues/170) merged last month. Part of the reasoning behind that proposal was that Engineers would have just been in the Sprint Kickoff Meeting prior to Open Standup, so the Team Updates were pretty redundant from that fact alone. However, since that RFC was merged, the Sprint Kickoff Meeting morphed into Product Team Office Hours.

This sorta leaves us in a state where it's worth reviewing our choice here to make sure we're going in the right direction. I was chatting with @ashfurrow about this and his thought was that we should either drop these updates completely or bring them back every week. I opted for the former for this RFC.

I don't get much value out of the team updates at Open Standup, but would love to know how others feel. I've been happy with getting this type of info from skimming the Sprint Overview email that goes out. On that last RFC there was def some interest in dropping these updates completely or changing the focus so those ideas are certainly in scope as well.

One additional advantage of dropping these updates is that the meeting might have a slightly less Product vibe and more of a meeting where Engineering can just be Engineering. 🤓 

## Exceptions:

There are times when teams have to share info with the rest of the group and Open Standup is a great avenue for this, so we should ensure there's still a good way for this to happen! If the info to share is covered by Cross-dependencies / Requests for Pairing or New Milestones / Repos / Blog posts sections, then great. Otherwise, the Closing Announcements section could be a good catch all.

## Additional Context:

The [Reduce Duplication at Engineering Open Standup](https://github.com/artsy/potential/issues/170) RFC from last month.

**Comment by orta** [comment]
Hah, now that's how you do a dramatic change, first do the minor stepping stone - then wrap it up.

**Comment by jonallured** [comment]
Ok folks, going to resolve this one with `Level of Support` at a `4: Acceptance, with Little Feedback`. I'll do a PR to yank the Team Lead updates over on the Open Standup doc. ✨✨✨

**Comment by orta** [comment]
This happened 👍
