### ISSUE TITLE
[RFC] New Hire Buddies

### ISSUE THREAD

**Issue by jonallured** [artsy/README#76]
Insight: assigning someone as a mentor to a new hire that has been at Artsy for a while is good because they know lots of things, but it's bad because it's probably been a long time since they set certain things up. Another new hire is in a much better position to assist with these types of things because they just solved these problems!

For example, @pepopowitz just started and @starsirius asked if I'd like to be a mentor for him and I was happy to. I was able to help with a couple questions he had. Later he was asking about creating AWS and Jira accounts - something I haven't really thought much about.

@javamonn (for example) would be better suited to help getting someone setup on Jira since he's just done it and I actually don't even remember how I did it. Similarly, @ashleyjelks has just setup her AWS creds and ran into gotchas - she's in a much better position to help him out.

As a bonus, it feels good when you're new to a company to be asked to help with things. Makes one feel like they know stuff and are being helpful!

So, I wonder if there's a way to connect new hires so that they can learn from each other. It could be as informal as a slack group or formalized by assigning buddies in some way. Open to ideas here!

**Comment by orta** [comment]
Nice, yeah, we've discussed this idea before and I've been a fan of the idea. 👍

**Comment by ashleyjelks** [comment]
I agree with the points raised here as well. WRT ideas about how to execute it effectively:

-perhaps new hires could be assigned a new hire contact person (not to replace the onboarding buddy/mentor role currently in place) to help with the sort of issues that come up when you first join an org and are trying to get everything set up and properly configured

-another idea could be an onboarding Slack group where more recent hires post config/onboarding specific questions and less recent hires are responsible for helping/pointing them in the right direction.

-another possibility here could be a point person list that is kept up to date so new folks know the best people to reach out to for specific questions? 

All suggestions here to take or leave, but great proposal!

**Comment by damassi** [comment]
Love this idea!

**Comment by dleve123** [comment]
> -perhaps new hires could be assigned a new hire contact person (not to replace the onboarding buddy/mentor role currently in place) to help with the sort of issues that come up when you first join an org and are trying to get everything set up and properly configured

👍 on this idea. I think it's really useful to have an explicit contact that's been at the org for a while to bombard with questions, but might also be helpful to have a peer new hire buddy to help with onboarding, ask other newbie questions to, etc. FWIW, when people start at roughly the same time, I think that happens informally and somewhat naturally - with that said, never hurts to be explicit.

**Comment by dblandin** [comment]
The [#onboarding-eng](https://artsy.slack.com/messages/CCC37HXE0) 🔒Slack channel has been a great resource for me this week.

**Comment by erikdstock** [comment]
I'm in favor of flagging recent onboardees as point people to mentees but wonder whether it needs to be a formal role. I'm not opposed to it, but wonder if it could lead to some overlap with mentor duties that make it unclear who is responsible for what.

**Comment by jonallured** [comment]
Ok, after chatting with @orta on this one, I'm proposing to resolve it with this PR:

https://github.com/artsy/README/pull/115

It seems like to a certain degree new hire buddies is happening organically, so I've just added a mention of the slack channel and then a nudge to have the new hire wave at the person most recently onboarded.

Thanks for all the feedback!! ❤️
