### ISSUE TITLE
20% Time Needs a Clear Definition

### ISSUE THREAD

**Issue by ashfurrow** [artsy/README#77]
## Proposal:

Define what "20% time" at Artsy is.

## Reasoning

20% time is important in determining project estimation, in giving engineers time for career growth, in keeping our systems happy, and more. But it lacks a clear definition – you can ask five PDDE staff what 20% is and get five different answers. Its relationship to [Future Fridays](https://github.com/artsy/potential/issues/146) is also not well-understood.

This leads to some teams, like Sell, having a strong culture of 20% time. However, other teams frequently mention a lack of using 20% in their sprint retrospectives. This leads to unnecessary feelings of ambiguity and uncertainty.

**PDDE Leadership should define 20% time** so we can reference it, apply it consistently, and iterate on the practice. I don't want to see comments attempting to define 20% time on this RFC; I'd prefer to follow-up after this RFC is accepted and define it somewhere authoritative.

Some key questions:

- Is it 20% of time per _person_ or per _team_?
- Is 20% time for learning new skills? (online courses, etc)
- Is 20% for product work only? For bug fixes only?
- Should 20% time work be ticketed in Jira. Should _all_ 20% time work be ticketed?

Feel free to add more questions in the comments – if the RFC is accepted, PDDE Leadership can address them.

## Exceptions:

None.

## Additional Context:

I brought this up in our [Q3 retrospective](https://www.notion.so/artsy/PDDE-Q3-Retro-815081f411d941e3bfe206b9835e09e1?p=e09d8bbe47ec4a67b9a30f88a5f79264).

**Comment by orta** [comment]
Related: https://github.com/artsy/potential/issues/146

**Comment by dblock** [comment]
We have two things here.

* _Small improvements and bug fixes_ that we already do as part of the normal development process. I believe an Engineer can today raise a work item that is, for example, pure technical debt, into this process via their tech lead and it gets backlogged and prioritized within this framework as anything else. Note that we _always_ want to have time for things like this.

* _True 20% time_ as in _do whatever you want that you think contributes to the business_. We currently don't do that. At other companies (eg. Google), 20% time often requires a sponsor, so that could be a way to do this. 

I propose we narrow this RFC down to (2).

**Comment by ashfurrow** [comment]
@dblock I don't quite agree – while both of those are important, I think we should accept this RFC as "we need to ask Product for a definition of 20% time" (1) _while also_ finding a structure for (2). In fact, we already have accepted an RFC for (2) but putting into practice has been challenging: https://github.com/artsy/potential/issues/146 I'll follow-up with the Product team about _this_ RFC to get a good definition of 20% time, and I'll talk to Joey about what we can work on together to get (2) addressed 👍

**Comment by joeyAghion** [comment]
To be clear, while feedback from engineers about https://github.com/artsy/potential/issues/146 was positive, I was unsuccessful among our collaborators. After off-site (where "creating safe opportunities to experiment and fail" was an explicit theme), we resolved to experiment with it again in a limited way within the Platform team.

I personally think some longer-outlook/experimental work _is_ appropriate for most engineering teams to protect some time for, but it's always been separate from the 20% introduced by Product and being discussed here.

**Comment by ashfurrow** [comment]
## Resolution
We decided we need a definition.

## Level of Support
3: Majority acceptance, with conflicting feedback.

#### Additional Context:
20% is _definitely_ different from longer-outlook/experimental engineering work, which is being experimented with on the Platform team.

## Next Steps
I'm meeting with Fatma on Friday to catch up, I'll ask her to give clarity to the PDDE org.

#### Exceptions
None.

**Comment by ashfurrow** [comment]
Follow-up: I spoke with Fatma today and she's going to look into getting this defined.

**Comment by ashfurrow** [comment]
Still following up with Fatma – as you might imagine, this is a busy time of year for budgets and things, but recent questions from new engineers during sprint planning have reiterated the need for clarity around 20% time.

**Comment by ashfurrow** [comment]
As shared in dB's Engineering Biweekly newsletter, the 20% definition is here: 
https://www.notion.so/artsy/20-time-fb501b4da22f4af9acf1826c0a34ab6b We're still working on a better name. Thanks again everyone!
